// Generated from the current CreditFacility Foundry artifact.
export const facilityAbi = [
{"type":"constructor","inputs":[{"name":"init","type":"tuple","internalType":"struct FacilityStore.Init","components":[{"name":"governor","type":"address","internalType":"address"},{"name":"borrower","type":"address","internalType":"address"},{"name":"asset","type":"address","internalType":"address"},{"name":"book","type":"address","internalType":"address"},{"name":"oracle","type":"address","internalType":"address"},{"name":"minPriceE8","type":"uint64","internalType":"uint64"},{"name":"maxOracleAge","type":"uint64","internalType":"uint64"},{"name":"advanceRateBps","type":"uint16","internalType":"uint16"},{"name":"maxLateBps","type":"uint16","internalType":"uint16"},{"name":"minJuniorBps","type":"uint16","internalType":"uint16"},{"name":"seniorAprBps","type":"uint64","internalType":"uint64"},{"name":"juniorAprBps","type":"uint64","internalType":"uint64"}]}],"stateMutability":"nonpayable"},
{"type":"function","name":"CHANGE_DELAY","inputs":[],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
{"type":"function","name":"MAX_LENDERS","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"acceptGovernor","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"accounting","inputs":[],"outputs":[{"name":"","type":"tuple","internalType":"struct FacilityMath.State","components":[{"name":"cash","type":"uint256","internalType":"uint256"},{"name":"drawn","type":"uint256","internalType":"uint256"},{"name":"seniorDrawn","type":"uint256","internalType":"uint256"},{"name":"seniorPrincipal","type":"uint256","internalType":"uint256"},{"name":"juniorPrincipal","type":"uint256","internalType":"uint256"},{"name":"seniorDeficit","type":"uint256","internalType":"uint256"},{"name":"juniorDeficit","type":"uint256","internalType":"uint256"},{"name":"seniorInterestDue","type":"uint256","internalType":"uint256"},{"name":"juniorInterestDue","type":"uint256","internalType":"uint256"},{"name":"seniorInterestCash","type":"uint256","internalType":"uint256"},{"name":"juniorInterestCash","type":"uint256","internalType":"uint256"},{"name":"residual","type":"uint256","internalType":"uint256"},{"name":"locked","type":"uint256","internalType":"uint256"},{"name":"seniorAprBps","type":"uint64","internalType":"uint64"},{"name":"juniorAprBps","type":"uint64","internalType":"uint64"},{"name":"advanceRateBps","type":"uint16","internalType":"uint16"},{"name":"maxLateBps","type":"uint16","internalType":"uint16"},{"name":"minJuniorBps","type":"uint16","internalType":"uint16"},{"name":"lastAccrual","type":"uint64","internalType":"uint64"},{"name":"recovery","type":"bool","internalType":"bool"}]}],"stateMutability":"view"},
{"type":"function","name":"approveLender","inputs":[{"name":"lender","type":"address","internalType":"address"},{"name":"approved","type":"bool","internalType":"bool"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"approvedLender","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
{"type":"function","name":"asset","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"availableDraw","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"bookEta","inputs":[],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
{"type":"function","name":"bookSurplus","inputs":[],"outputs":[{"name":"extra","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
{"type":"function","name":"borrower","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"borrowingBase","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"cancelTerms","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"deposit","inputs":[{"name":"tranche","type":"uint8","internalType":"enum FacilityStore.Tranche"},{"name":"assets","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"shares","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
{"type":"function","name":"draw","inputs":[{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"executeBook","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"executeOracle","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"executeTerms","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"governor","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"juniorClaim","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"juniorIndex","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"juniorIndexOf","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"juniorShares","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"juniorSupply","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"lenderCount","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"maxOracleAge","inputs":[],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
{"type":"function","name":"minPriceE8","inputs":[],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
{"type":"function","name":"oracle","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"oracleEta","inputs":[],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
{"type":"function","name":"pendingBook","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"pendingGovernor","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"pendingMaxAge","inputs":[],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
{"type":"function","name":"pendingMinPrice","inputs":[],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
{"type":"function","name":"pendingOracle","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"poke","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"receivables","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"recognizeLoss","inputs":[],"outputs":[{"name":"loss","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
{"type":"function","name":"redeem","inputs":[{"name":"tranche","type":"uint8","internalType":"enum FacilityStore.Tranche"},{"name":"shares","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"assets","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
{"type":"function","name":"repay","inputs":[{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"scheduleBook","inputs":[{"name":"book","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"scheduleOracle","inputs":[{"name":"next","type":"address","internalType":"address"},{"name":"minPrice","type":"uint64","internalType":"uint64"},{"name":"maxAge","type":"uint64","internalType":"uint64"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"scheduleTerms","inputs":[{"name":"next","type":"tuple","internalType":"struct FacilityStore.PendingTerms","components":[{"name":"advanceRateBps","type":"uint16","internalType":"uint16"},{"name":"maxLateBps","type":"uint16","internalType":"uint16"},{"name":"minJuniorBps","type":"uint16","internalType":"uint16"},{"name":"seniorAprBps","type":"uint64","internalType":"uint64"},{"name":"juniorAprBps","type":"uint64","internalType":"uint64"},{"name":"eta","type":"uint64","internalType":"uint64"},{"name":"active","type":"bool","internalType":"bool"}]}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"seenLender","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
{"type":"function","name":"seniorClaim","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"seniorIndex","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"seniorIndexOf","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"seniorShares","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"seniorSupply","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"solvent","inputs":[],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
{"type":"function","name":"sweepResidual","inputs":[{"name":"to","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"tightenAdvanceRate","inputs":[{"name":"bps","type":"uint16","internalType":"uint16"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"tightenMaxLate","inputs":[{"name":"bps","type":"uint16","internalType":"uint16"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"tightenMinJunior","inputs":[{"name":"bps","type":"uint16","internalType":"uint16"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"transferGovernor","inputs":[{"name":"next","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"withdrawInterest","inputs":[{"name":"tranche","type":"uint8","internalType":"enum FacilityStore.Tranche"}],"outputs":[{"name":"amount","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
{"type":"event","name":"BookScheduled","inputs":[{"name":"book","type":"address","indexed":true,"internalType":"address"},{"name":"eta","type":"uint64","indexed":false,"internalType":"uint64"}],"anonymous":false},
{"type":"event","name":"BookSet","inputs":[{"name":"book","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
{"type":"event","name":"Deposited","inputs":[{"name":"lender","type":"address","indexed":true,"internalType":"address"},{"name":"tranche","type":"uint8","indexed":false,"internalType":"enum FacilityStore.Tranche"},{"name":"assets","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"shares","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"Drawn","inputs":[{"name":"borrower","type":"address","indexed":true,"internalType":"address"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"GovernorSet","inputs":[{"name":"governor","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
{"type":"event","name":"GovernorTransferStarted","inputs":[{"name":"pending","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
{"type":"event","name":"InterestPaid","inputs":[{"name":"lender","type":"address","indexed":true,"internalType":"address"},{"name":"tranche","type":"uint8","indexed":false,"internalType":"enum FacilityStore.Tranche"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"LenderApproved","inputs":[{"name":"lender","type":"address","indexed":true,"internalType":"address"},{"name":"approved","type":"bool","indexed":false,"internalType":"bool"}],"anonymous":false},
{"type":"event","name":"LossRecognized","inputs":[{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"OracleScheduled","inputs":[{"name":"oracle","type":"address","indexed":true,"internalType":"address"},{"name":"eta","type":"uint64","indexed":false,"internalType":"uint64"}],"anonymous":false},
{"type":"event","name":"OracleSet","inputs":[{"name":"oracle","type":"address","indexed":true,"internalType":"address"},{"name":"minPriceE8","type":"uint64","indexed":false,"internalType":"uint64"},{"name":"maxOracleAge","type":"uint64","indexed":false,"internalType":"uint64"}],"anonymous":false},
{"type":"event","name":"RecoveryEntered","inputs":[{"name":"drawnAfter","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"Redeemed","inputs":[{"name":"lender","type":"address","indexed":true,"internalType":"address"},{"name":"tranche","type":"uint8","indexed":false,"internalType":"enum FacilityStore.Tranche"},{"name":"shares","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"assets","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"Repaid","inputs":[{"name":"payer","type":"address","indexed":true,"internalType":"address"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"ResidualSwept","inputs":[{"name":"to","type":"address","indexed":true,"internalType":"address"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"SurplusBooked","inputs":[{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"TermsCancelled","inputs":[],"anonymous":false},
{"type":"event","name":"TermsExecuted","inputs":[{"name":"advanceRateBps","type":"uint16","indexed":false,"internalType":"uint16"},{"name":"maxLateBps","type":"uint16","indexed":false,"internalType":"uint16"},{"name":"minJuniorBps","type":"uint16","indexed":false,"internalType":"uint16"},{"name":"seniorAprBps","type":"uint64","indexed":false,"internalType":"uint64"},{"name":"juniorAprBps","type":"uint64","indexed":false,"internalType":"uint64"}],"anonymous":false},
{"type":"event","name":"TermsScheduled","inputs":[{"name":"advanceRateBps","type":"uint16","indexed":false,"internalType":"uint16"},{"name":"maxLateBps","type":"uint16","indexed":false,"internalType":"uint16"},{"name":"minJuniorBps","type":"uint16","indexed":false,"internalType":"uint16"},{"name":"seniorAprBps","type":"uint64","indexed":false,"internalType":"uint64"},{"name":"juniorAprBps","type":"uint64","indexed":false,"internalType":"uint64"},{"name":"eta","type":"uint64","indexed":false,"internalType":"uint64"}],"anonymous":false},
{"type":"event","name":"TermsTightened","inputs":[{"name":"advanceRateBps","type":"uint16","indexed":false,"internalType":"uint16"},{"name":"maxLateBps","type":"uint16","indexed":false,"internalType":"uint16"},{"name":"minJuniorBps","type":"uint16","indexed":false,"internalType":"uint16"}],"anonymous":false},
{"type":"error","name":"BadParam","inputs":[]},
{"type":"error","name":"Covenant","inputs":[]},
{"type":"error","name":"LenderCap","inputs":[]},
{"type":"error","name":"NotRecovery","inputs":[]},
{"type":"error","name":"ReentrancyGuardReentrantCall","inputs":[]},
{"type":"error","name":"SafeERC20FailedOperation","inputs":[{"name":"token","type":"address","internalType":"address"}]},
{"type":"error","name":"SeniorFirst","inputs":[]},
{"type":"error","name":"TooEarly","inputs":[]},
{"type":"error","name":"TrancheWiped","inputs":[]},
{"type":"error","name":"Unauthorized","inputs":[]},
{"type":"error","name":"Unclaimed","inputs":[]}
] as const;
