import type { Snapshot } from "../chain/model";
import { DEPLOYMENT } from "../chain/config";
import { zeroAddress } from "viem";
const U = 1_000_000n;
const S = 10n ** 18n;
export function previewSnapshot(): Snapshot {
  const now = BigInt(Math.floor(Date.now() / 1000));
  const p = {
    address: DEPLOYMENT.platform,
    name: "Weekly credit platform",
    share: zeroAddress,
    issuer: zeroAddress,
    nav: U,
    cash: 1200n * U,
    nextWindow: now + 420n,
    windowInterval: 600n,
    gated: false,
    queueLength: 3n,
    queuedValue: 900n * U,
    limit: 10000n * U,
    exposure: 2400n * U,
    reserve: 750n * U,
    holding: 1200n * S,
    blocked: false,
    requests: [
      {
        id: 1n,
        owner: zeroAddress,
        shares: 250n * S,
        navValue: 250n * U,
        requestedAt: now - 3600n,
        status: "Queued" as const,
        advanceId: 0n,
      },
    ],
    settlement: { cashBalance: 1200n * U, repayFirst: 2400n * U, queuePayable: 0n, queueShortfall: 900n * U },
  };
  return {
    mode: "preview",
    blockNumber: 0n,
    observedAt: Date.now(),
    usdgBalance: 500n * U,
    roles: { operator: false, issuerPlatforms: [], partnerVaults: [] },
    platforms: [p],
    creditLine: {
      owner: zeroAddress,
      capital: 7600n * U,
      outstanding: 2376n * U,
      totalExposure: 2400n * U,
      earnedFees: 124n * U,
      lateOutstanding: 0n,
      utilizationBps: 2382,
      paused: false,
      advances: [
        {
          id: 1n,
          source: p.address,
          to: zeroAddress,
          principal: 1485n * U,
          fee: 15n * U,
          drawnAt: now - 3600n,
          dueAt: now + 420n,
          status: "Active",
          remaining: 1500n * U,
          recovered: 0n,
          grace: 60n,
        },
        {
          id: 2n,
          source: p.address,
          to: zeroAddress,
          principal: 891n * U,
          fee: 9n * U,
          drawnAt: now - 2400n,
          dueAt: now + 420n,
          status: "Active",
          remaining: 900n * U,
          recovered: 0n,
          grace: 60n,
        },
        {
          id: 3n,
          source: p.address,
          to: zeroAddress,
          principal: 1188n * U,
          fee: 12n * U,
          drawnAt: now - 86400n,
          dueAt: now - 86000n,
          status: "Repaid",
          remaining: 0n,
          recovered: 1200n * U,
          grace: 60n,
        },
      ],
    },
    vaults: [
      {
        address: DEPLOYMENT.vaultA,
        name: "Partner vault A",
        owner: zeroAddress,
        idle: 20000n * U,
        reserveCash: 0n,
        outstandingPrincipal: 0n,
        totalAssets: 20000n * U,
        paused: false,
        mandate: {
          partner: zeroAddress,
          signer: zeroAddress,
          minFeeBps: 25,
          maxTenor: 86400n * 30n,
          concentrationBps: 5000,
          expiry: now + 86400n * 90n,
        },
        approvedPlatforms: [p.address],
        advanceCount: 0n,
        proposals: [],
      },
    ],
    warnings: ["All amounts in this mode are illustrative. No wallet actions are available."],
  };
}
