import { useRef } from 'react';
import { X } from 'lucide-react';
import { useDialog } from '../ui/dialog';
import { Button, Notice, Rows } from './Common';
import type { DemoGateway, DemoState } from './types';
export function DemoSheet({state,gateway,busy,run,refresh,close}:{state:DemoState;gateway:DemoGateway;busy:boolean;run:<T>(task:()=>Promise<T>)=>Promise<T>;refresh:()=>Promise<void>;close:()=>void}) {
 const ref=useRef<HTMLElement>(null);
 useDialog(ref,close,busy);
 return <div className="dg-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)close();}}><section ref={ref} className="dg-sheet" role="dialog" aria-modal="true" aria-labelledby="demo-title" tabIndex={-1}><div className="dg-card-top"><span className="dg-badge">{state.environment||'TEST setup · chain 421614'}</span><button className="dg-icon-button" aria-label="Close Demo" disabled={busy} onClick={close}><X size={20}/></button></div><h2 id="demo-title">Demo setup</h2><p>Prepare this wallet with supported TEST assets.</p><Rows items={[["Test gas",`${state.setup.gas} ETH`],["Test USDG",`${state.setup.usdg} USDG`]]}/>{state.setup.message&&<Notice>{state.setup.message}</Notice>}{state.setup.canGetGas!==undefined&&<div className="dg-setup-item"><h3>Get test gas</h3><p>Open the Arbitrum Sepolia faucet to request test ETH.</p><a className="dg-button dg-secondary" href="https://www.alchemy.com/faucets/arbitrum-sepolia" target="_blank" rel="noopener noreferrer">Get test gas</a></div>}<div className="dg-setup-item"><h3>Get test USDG</h3><p>Open the Paxos faucet and select USDG on Arbitrum Sepolia.</p><a className="dg-button dg-secondary" href="https://faucet.paxos.com/" target="_blank" rel="noopener noreferrer">Get test USDG</a></div><div className="dg-setup-item"><h3>Mint test position</h3><p>{state.setup.mintDescription||'Complete TEST identity verification to check supported issuance.'}</p><Button disabled={!state.setup.canMint||!state.setup.mintDescription} busy={busy} onClick={()=>void run(async()=>{await gateway.mintPosition();await refresh();}).catch(()=>{})}>Mint test position</Button></div><div className="dg-actions"><Button secondary busy={busy} onClick={()=>void run(refresh).catch(()=>{})}>Check setup</Button></div><p className="dg-caption">Submitted transactions stay in your history. Closing this sheet does not cancel them.</p></section></div>;
}
