import { useState } from 'react';
import { ArrowUpRight, Check, ShieldCheck, Wallet } from 'lucide-react';
import { z } from 'zod';
import { roles } from './fixtures';
import { IdentityDialog } from './IdentityDialog';
import { Button, Heading, Rows } from './Common';
import type { DemoRole, Enquiry, EnquiryReceipt } from './types';
export function WalletEntry({connect,busy}:{connect:()=>void;busy:boolean}) {
 return <section className="dg-welcome dg-wallet-entry"><span className="dg-entry-icon"><Wallet size={27}/></span><Heading title="Your next step starts here." copy="Connect your wallet to find your Lockgate workspace."/><Button onClick={connect} busy={busy}>Connect wallet <ArrowUpRight size={17}/></Button><p className="dg-caption">You’ll sign a message to check your profile. No funds move.</p></section>;
}
export function RoleEntry({choose,busy,existingRoles=[],back}:{choose:(role:DemoRole)=>void;busy:boolean;existingRoles?:DemoRole[];back?:()=>void}) {
 return <section className="dg-welcome">{back&&<div className="dg-add-profile-back"><Button secondary disabled={busy} onClick={back}>Back to dashboard</Button></div>}<Heading title={back?'Add a new profile.':'Choose your path.'} copy={back?'Choose how you’d like to use this wallet.':'Get started, or talk with our team.'}/><div className="dg-role-grid">{roles.map((role,index)=>{
  const exists=existingRoles.includes(role.id);
  return <article className="dg-role-card" key={role.id}><div className="dg-card-top"><span className="dg-entry-icon"><role.icon size={22}/></span><span className="dg-number">0{index+1}</span></div><h2>{role.title}</h2><p>{role.description}</p><button className="dg-button dg-role-cta" data-profile-exists={exists||undefined} disabled={busy||exists} onClick={()=>choose(role.id)} aria-label={`${exists?'Profile already exists':role.cta} — ${role.title}`}>{exists?'Profile already exists':role.cta}{exists?<Check size={16}/>:<ArrowUpRight size={16}/>}</button></article>;
 })}</div></section>;
}
export function IdentityEntry({onSelect,busy,preparing=false,error}:{onSelect:(id:string)=>void;busy:boolean;preparing?:boolean;error?:string}) {
 const [started,setStarted]=useState(false);
 return <section className="dg-narrow"><Heading title="Let’s verify your identity." copy="Choose a identity to continue."/><div className="dg-panel"><ShieldCheck size={26}/><h2>Identity first</h2><p>Choose one of ten preverified profiles to link to your wallet.</p><div className="dg-actions"><Button busy={preparing} disabled={busy} onClick={()=>setStarted(true)}>{preparing?'Preparing identity check…':'Start KYC'} <ArrowUpRight size={16}/></Button></div></div>{started&&<IdentityDialog onClose={()=>setStarted(false)} onSelect={onSelect} busy={busy} error={error}/>}</section>;
}
const enquirySchema=z.object({representative:z.string().trim().min(2,'Enter your name.').max(100),email:z.email('Enter a valid work email.').max(254),organization:z.string().trim().min(2,'Enter your organization.').max(150),jurisdiction:z.string().trim().min(2,'Enter your jurisdiction.').max(100),summary:z.string().trim().min(20,'Tell us a little more (at least 20 characters).').max(1500)});
export function EnquiryForm({role,submit,busy,back}:{role:'originator'|'manager';submit:(value:Enquiry)=>Promise<EnquiryReceipt>;busy:boolean;back:()=>void}) {
 const [fields,setFields]=useState({representative:'',email:'',organization:'',jurisdiction:'',summary:''});
 const [errors,setErrors]=useState<Record<string,string>>({});
 const [receipt,setReceipt]=useState<EnquiryReceipt>();
 const [review,setReview]=useState(false);
 const isFirm=role==='manager';
 if(receipt)return <section className="dg-narrow"><Heading title="Your enquiry is received." copy="Our team will review your details and follow up."/><div className="dg-panel"><span className="dg-entry-icon"><Check/></span><h2>Thank you, {fields.representative}.</h2><Rows items={[["Reference",receipt.reference],["Organization",fields.organization],["Acknowledgement email",receipt.emailStatus],["Received",receipt.receivedAt]]}/><p>An enquiry starts the conversation. Approval, agreements and activation follow a separate review.</p><div className="dg-actions"><Button onClick={back} secondary>Back to your workspace</Button></div></div></section>;
 return <section className="dg-narrow"><Heading eyebrow={isFirm?'03 · Licensed investment firm':'02 · Originating fund / platform'} title={review?'Review your enquiry.':'Let’s talk.'} copy={isFirm?'Tell us about your firm and investment mandate.':'Tell us about your assets and investor exit needs.'} back={()=>review?setReview(false):back()}/><form className="dg-panel dg-form" onSubmit={async e=>{e.preventDefault();if(!review){const parsed=enquirySchema.safeParse(fields);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(i=>[String(i.path[0]),i.message])));return;}setFields(parsed.data);setErrors({});setReview(true);return;}try{setReceipt(await submit({...fields,role}));}catch{/* Parent renders the service error; form remains intact. */}}}>
 {review?<><Rows items={[["Representative",fields.representative],["Work email",fields.email],["Organization",fields.organization],["Jurisdiction",fields.jurisdiction]]}/><h2>Your enquiry</h2><p className="dg-preserve">{fields.summary}</p></>:<div className="dg-form-grid">{([['representative','Representative name'],['email','Work email'],['organization','Organization'],['jurisdiction','Jurisdiction']] as const).map(([key,label])=><label key={key}>{label}<input required maxLength={key==='email'?254:150} autoComplete={key==='email'?'email':key==='representative'?'name':key==='organization'?'organization':'country-name'} type={key==='email'?'email':'text'} value={fields[key]} onChange={e=>setFields({...fields,[key]:e.target.value})} aria-invalid={Boolean(errors[key])} aria-describedby={errors[key]?`error-${key}`:undefined}/>{errors[key]&&<span id={`error-${key}`} className="dg-field-error">{errors[key]}</span>}</label>)}<label className="dg-full">{isFirm?'Mandate and vehicle plans':'Assets and exit needs'}<textarea required minLength={20} maxLength={1500} rows={4} value={fields.summary} onChange={e=>setFields({...fields,summary:e.target.value})} aria-invalid={Boolean(errors.summary)}/>{errors.summary&&<span className="dg-field-error">{errors.summary}</span>}</label></div>}
 <p className="dg-caption">We use these details to respond to your enquiry and coordinate onboarding.</p><Button type="submit" busy={busy}>{review?'Send enquiry':'Review enquiry'}<ArrowUpRight size={16}/></Button></form></section>;
}
