import { useState } from 'react';
import { SigningProgress } from './SigningProgress';
import { AgreementDocument } from './AgreementDocument';
import { ChainReference } from './ChainReference';
import { parseUnits } from 'viem';
import { ArrowUpRight } from 'lucide-react';
import { Button, Heading, money, Notice, Rows } from './Common';
import type { DemoGateway, DemoState, PreparedSubscription, Receipt, Vehicle, WalletProgress } from './types';
type Props={state:DemoState;gateway:DemoGateway;run:<T>(task:()=>Promise<T>)=>Promise<T>;busy:boolean;refresh:()=>Promise<void>};
export function Provider({state,gateway,run,busy,refresh}:Props) {
 const [progress,setProgress]=useState<WalletProgress>();
 const [vehicleId,setVehicleId]=useState('');
 const [amount,setAmount]=useState('');
 const [withdraw,setWithdraw]=useState('');
 const [prepared,setPrepared]=useState<PreparedSubscription>();
 const [receipt,setReceipt]=useState<Receipt>();
 const [stage,setStage]=useState<'vehicle'|'terms'|'position'>('vehicle');
 const vehicle=state.vehicles.find(v=>v.id===vehicleId);
 const signed=Boolean(vehicle?.agreement?.signed&&!vehicle.agreement.funded&&vehicle.agreement.amount&&sameAmount(vehicle.agreement.amount,amount));
 const reviewedText=signed?vehicle?.agreement?.text:prepared?.message;
 const reviewedDigest=signed?vehicle?.agreement?.digest:prepared?.digest;
 const reviewedVersion=signed?vehicle?.agreement?.version:prepared?.version;
 const positive=(s:string)=>/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/.test(s)&&Number(s)>0;
 const choose=(v:Vehicle)=>{setProgress(undefined);setVehicleId(v.id);setStage([v.providerPrincipal,v.providerNav,v.queued,v.claimable].some(n=>Number(n)>0)||v.withdrawals?.length?'position':'vehicle');setPrepared(undefined);setAmount('');setReceipt(undefined);};
 if(!vehicle)return <section><Heading eyebrow="04 · Capital provider" title="Choose your investment vehicle." copy="Invest through an eligible firm. Each vehicle has its own mandate and terms."/><div className="dg-vehicle-grid">{state.vehicles.map(v=><article className="dg-panel" key={v.id}><span className="dg-badge">TEST vehicle</span><h2>{v.name}</h2><p>{v.firm}</p><Rows items={[["Vehicle NAV",`${money(v.nav)} USDG`],["Available cash",`${money(v.cash)} USDG`],["Minimum subscription",`${money(v.minimum)} USDG`]]}/><Button onClick={()=>choose(v)} disabled={busy}>View vehicle <ArrowUpRight size={16}/></Button></article>)}</div>{state.vehicles.length===0&&<div className="dg-panel"><h2>No vehicles are available.</h2><p>Refresh to check registered vehicles and current readiness.</p></div>}</section>;
 return <section className="dg-narrow"><Heading eyebrow={vehicle.firm} title={stage==='position'?'Your vehicle interest.':stage==='terms'?'Review your subscription.':vehicle.name} copy={stage==='position'?vehicle.name:'Your capital is managed under this vehicle’s mandate.'} back={()=>{setVehicleId('');setStage('vehicle');}}/>{receipt&&<Notice><strong>{receipt.title}</strong> · {receipt.status}{receipt.amount&&` · ${money(receipt.amount)} USDG`} <ChainReference value={receipt.hash||receipt.id} transaction/> <a href="#/records">View transactions</a></Notice>}
 {stage==='position'?<><div className="dg-panel"><h2>Personal ledger</h2><Rows items={[["Your principal",`${money(vehicle.providerPrincipal)} USDG`],["Your NAV",`${money(vehicle.providerNav)} USDG`],["Income allocated",`${money(vehicle.income)} USDG`],["Loss allocated",`${money(vehicle.loss)} USDG`],["Available to withdraw",`${money(vehicle.withdrawable)} USDG`],["Withdrawal queue",`${money(vehicle.queued)} USDG`],["Ready to claim",`${money(vehicle.claimable)} USDG`]]}/><p>Your individual interest is recorded by the vehicle. The firm selects investments within its mandate.</p><div className="dg-actions"><Button onClick={()=>setStage('vehicle')} secondary>Add capital</Button><Button secondary onClick={()=>downloadStatement(vehicle,state)}>Download statement</Button></div></div><div className="dg-panel"><h2>Withdraw capital</h2><p>Available cash is paid under the vehicle policy. Unavailable amounts enter the withdrawal queue.</p><label className="dg-field">Amount in USDG<input inputMode="decimal" value={withdraw} onChange={e=>setWithdraw(e.target.value)} disabled={busy}/></label><Button disabled={!positive(withdraw)} busy={busy} onClick={()=>void run(async()=>{setReceipt(await gateway.withdraw(vehicle.id,withdraw));await refresh();setWithdraw('');}).catch(()=>{})}>Request withdrawal</Button></div><div className="dg-panel"><h2>Withdrawal queue</h2>{vehicle.withdrawals?.map(w=><div className="dg-queue-row" key={w.id}><span>{money(w.amount)} USDG <small>Request {w.id}</small></span><Button secondary busy={busy} disabled={!w.cancelable} onClick={()=>void run(async()=>{setReceipt(await gateway.providerAction(vehicle.id,'cancel',w.id));await refresh();}).catch(()=>{})}>Cancel unfilled</Button></div>)}<div className="dg-actions"><Button secondary busy={busy} disabled={!Number(vehicle.queued)} onClick={()=>void run(async()=>{setReceipt(await gateway.providerAction(vehicle.id,'processQueue'));await refresh();}).catch(()=>{})}>Check queue</Button><Button busy={busy} disabled={!Number(vehicle.claimable)} onClick={()=>void run(async()=>{setReceipt(await gateway.providerAction(vehicle.id,'claim'));await refresh();}).catch(()=>{})}>Claim {money(vehicle.claimable)} USDG</Button></div></div></>:<>
 <div className="dg-panel"><h2>Vehicle policy</h2><p className="dg-preserve">{vehicle.policy}</p><Rows items={[["Minimum subscription",`${money(vehicle.minimum)} USDG`],["Vehicle eligibility",vehicle.eligibilityStatus],["Settlement asset","TEST USDG"]]}/>{!vehicle.eligible?<Button busy={busy} onClick={()=>void run(async()=>{await gateway.checkEligibility(vehicle.id);await refresh();}).catch(()=>{})}>Check my eligibility</Button>:<span className="dg-badge">Eligible for this vehicle</span>}</div>
 {vehicle.eligible&&<div className="dg-panel"><label className="dg-field">Subscription amount<div className="dg-amount"><input aria-label="Subscription amount" inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setPrepared(undefined);}} disabled={busy||stage==='terms'}/><span>USDG</span></div></label>{stage!=='terms'&&<div className="dg-actions"><Button disabled={!positive(amount)||Number(amount)<Number(vehicle.minimum)} busy={busy} onClick={()=>void run(async()=>{const document=await gateway.prepareSubscription(vehicle.id,amount);setPrepared(document);setStage('terms');}).catch(()=>{})}>Review terms</Button></div>}{stage==='terms'&&reviewedText&&reviewedDigest&&<><SigningProgress kind="fund" progress={progress} signed={signed&&Boolean(vehicle.agreement?.accepted)}>{signed&&<div className="dg-actions"><Button disabled={!vehicle.agreement?.accepted} busy={busy} onClick={()=>void run(async()=>{try{setReceipt(await gateway.fund(vehicle.id,amount,setProgress));await refresh();setStage('position');}catch(error){setProgress(undefined);throw error;}}).catch(()=>{})}>Approve & fund {money(amount)} USDG</Button></div>}</SigningProgress><AgreementDocument key={reviewedDigest} title={signed?vehicle.agreement?.title||'Vehicle subscription agreement':'Vehicle subscription agreement'} text={reviewedText} version={reviewedVersion||'2'} documentId={signed?vehicle.agreement?.id||'':prepared?.documentId||''} digest={reviewedDigest} identityName={state.profile.identity?.name||''} signerName={vehicle.agreement?.signerName} signed={signed} busy={busy} expiresAt={signed?undefined:prepared?.expiresAt} signLabel="Sign subscription" onSign={name=>void run(async()=>{if(!prepared)throw new Error('Retrieve current subscription terms before signing.');try{await gateway.signSubscription(vehicle.id,amount,prepared,name,true,setProgress);await refresh();}catch(error){setProgress(undefined);throw error;}}).catch(()=>{})}>{signed&&!vehicle.agreement?.accepted&&<Notice>Subscription signed. The firm must accept it before funding.</Notice>}</AgreementDocument><div className="dg-actions"><Button secondary onClick={()=>{setStage('vehicle');setPrepared(undefined);setProgress(undefined);}} disabled={busy}>Edit amount</Button></div></>}{stage==='terms'&&(!reviewedText||!reviewedDigest)&&<Notice>Current subscription terms are unavailable. Go back and request the exact agreement before signing.</Notice>}</div>}
 </>}
 </section>;
}

function sameAmount(a:string,b:string){try{return parseUnits(a,6)===parseUnits(b,6);}catch{return false;}}
function downloadStatement(vehicle:Vehicle,state:DemoState){
 const payload={document:'Lockgate TEST vehicle statement',exportedAt:new Date().toISOString(),environment:state.environment,identity:state.profile.identity?.identityRef,vehicle,records:state.receipts};
 const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));
 const anchor=document.createElement('a');anchor.href=url;anchor.download=`lockgate-${vehicle.id}-statement.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
