import { ArrowRight, ArrowUpRight, Wallet } from 'lucide-react';
import { Button, Heading, money, Notice, Rows } from './Common';
import type { PublicOverview } from './types';
export function PublicHome({overview,error,retry,connect,busy}:{overview?:PublicOverview;error:string;retry:()=>void;connect:()=>void;busy:boolean}) {
 return <section><div className="dg-public-heading"><Heading eyebrow="The Lockgate exit desk" title="An earlier exit, on your terms." copy="Explore current liquidity, then connect your wallet to find your workspace."/><Button onClick={connect} busy={busy}><Wallet size={17}/>Connect wallet <ArrowUpRight size={16}/></Button></div>{error&&<Notice error>Public metrics are unavailable. {error} <button className="dg-back" onClick={retry}>Retry</button></Notice>}<div className="dg-public-metrics" aria-label="Public protocol metrics">{[['Supported originators',overview?.originators],['Investment firms',overview?.firms],['Available cash',overview?`${money(overview.availableCash)} USDG`:undefined],['Outstanding exposure',overview?`${money(overview.outstanding)} USDG`:undefined]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value??'—'}</strong></div>)}</div><div className="dg-columns"><article className="dg-panel"><span className="dg-eyebrow">For existing investors</span><h2>Find your supported positions.</h2><p>Identity matching connects your investments to eligible offers. Review your net payout before signing.</p><div className="dg-actions"><Button secondary onClick={connect} busy={busy}>Get started <ArrowRight size={16}/></Button></div></article><article className="dg-panel"><span className="dg-eyebrow">Know the terms</span><h2>Read the platform policies.</h2><p>See supported instruments and permitted settlement routes before connecting.</p><div className="dg-actions"><a className="dg-button dg-secondary" href="#/terms">Explore platform terms <ArrowUpRight size={16}/></a></div></article></div><p className="dg-caption">Connect and sign a message to access your profile. No funds move during sign-in.</p></section>;
}
export function PublicTerms({overview,error,retry}:{overview?:PublicOverview;error:string;retry:()=>void}) {
 return <section><a className="dg-back" href="#/">← Back to overview</a><Heading eyebrow="Public information" title="Explore platform terms." copy="Supported instruments and permitted routes. Your exact agreement is shown before signing."/>{error&&<Notice error>{error} <button className="dg-back" onClick={retry}>Retry</button></Notice>}{!overview?(error?null:<Notice>Reading platform terms…</Notice>):!overview.platforms?.length?<div className="dg-panel"><h2>Platform terms are unavailable.</h2><p>No current public platform terms have been returned by the registry.</p></div>:<div className="dg-vehicle-grid">{overview.platforms.map(p=><article key={p.id} className="dg-panel"><span className="dg-badge">{p.status}</span><h2>{p.name}</h2><Rows items={[["Instrument",p.instrument],["Permitted routes",p.routes.join(' · ')]]}/><p className="dg-preserve">{p.terms}</p></article>)}</div>}</section>;
}
