import type { Address, Hex } from 'viem';
export type DemoRole = 'investor' | 'originator' | 'manager' | 'provider';
export type Identity = { id:string; name:string; jurisdiction:string; identityRef:string; fixtureCase:'match'|'mismatch'|'empty' };
export type Profile = { identity?:Identity; roles:DemoRole[]; activeRole?:DemoRole; onboarding?:string; organization?:string };
export type Position = { id:string; name:string; originator:string; instrument:string; available:string; faceValue:string; partial:boolean; restriction?:string };
export type Offer = { id:string; positionId?:string; vehicleId:string; firm:string; vehicle:string; route:'purchase'|'finance'; amount:string; payout:string; fee:string; residual:string; expiresAt:string; agreement:Agreement };
export type Agreement = { id:string; version:string; title:string; text:string; digest:Hex; signed:boolean; accepted:boolean; funded?:boolean; amount?:string; signerName?:string };
export type AgreementRecord = {id:string;title:string;version:string;text:string;digest:Hex;signedAt?:string;signerName?:string;status:string;receiptId?:string};
export type DraftDocument = {id:string;kind:'exit'|'subscription';title:string;text:string;digest:Hex;version:string;createdAt:string;expiresAt:string;positionId?:string;vehicleId:string;amount:string};
export type ResumedDocument = {kind:'exit';offer:Offer}|{kind:'subscription';prepared:PreparedSubscription;vehicleId:string;amount:string};
export type Reservation = {digest:Hex;positionId:string;units:string;payout:string;expiresAt:string;firm:string};
export type Vehicle = { id:string; name:string; firm:string; cash:string; nav:string; policy:string; policyText?:string; policyHash?:Hex; policyVersion?:string; minimum:string; eligible:boolean; eligibilityStatus:string; agreement?:Agreement; providerPrincipal?:string; providerNav?:string; income?:string; loss?:string; withdrawable?:string; queued?:string; claimable?:string; withdrawals?:{id:string;amount:string;cancelable:boolean}[]; address?:Address };
export type Receipt = { id:string; title:string; status:'submitted'|'confirmed'|'reverted'|'unknown'; hash?:Hex; explorerUrl?:string; amount?:string; residual?:string; createdAt:string; account:Address; detail?:string };
export type Workspace = { title:string; organization:string; status:string; checks:{label:string; status:string}[]; records:{id:string; label:string; value:string}[]; actions?:WorkspaceAction[] };
export type WorkspaceAction = { id:string; label:string; description:string; kind:'register'|'repay'|'mandate'|'approve'; fields:{key:string; label:string; value?:string; type:'text'|'amount'; required:boolean; options?:{value:string;label:string}[]}[]; disabledReason?:string };
export type PublicOverview = { originators:number; firms:number; availableCash:string; outstanding:string; environment:string; platforms?:{id:string;name:string;instrument:string;routes:string[];terms:string;status:string}[] };
export type DemoState = { environment?:string; profile:Profile; positions:Position[]; positionStatus:'matched'|'empty'|'mismatch'|'unavailable'; vehicles:Vehicle[]; receipts:Receipt[]; agreements?:AgreementRecord[]; documentDrafts?:DraftDocument[]; reservations?:Reservation[]; workspace?:Workspace; setup:{gas:string; usdg:string; canMint:boolean; canFund:boolean; canGetGas?:boolean; canGetUsdg?:boolean; gasAmount?:string; gasFaucetUrl?:string; mintDescription?:string; fundingAmount?:string; message?:string}; deploymentReady:boolean };
export type Enquiry = { role:'originator'|'manager'; representative:string; email:string; organization:string; jurisdiction:string; summary:string };
export type EnquiryReceipt = { reference:string; receivedAt:string; emailStatus:string };
export type PreparedSubscription = {message:string;digest:Hex;vault:Address;amount:string;termsHash:Hex;signerName:string;expiresAt:string;documentId:string;version:'2'};
export type WalletProgress = {phase:'reservation-pending'|'signature-requested'|'signature-collected'|'acceptance-pending'|'acceptance-confirmed'|'transaction-requested'|'transaction-submitted'|'transaction-confirmed'|'transaction-unknown'|'approval-requested'|'approval-submitted'|'approval-confirmed';hash?:Hex};
/** Adapter must authenticate private reads and return authoritative receipt-backed results. */
export interface DemoGateway {
 publicOverview():Promise<PublicOverview>;
 authenticate(account:Address, chainId:number):Promise<DemoState>;
 refresh(account:Address, chainId:number):Promise<DemoState>;
 selectRole(role:DemoRole,intent?:'create'|'switch'):Promise<DemoState>;
 selectIdentity(profileId:string,onBound?:()=>void):Promise<DemoState>;
 enquire(enquiry:Enquiry):Promise<EnquiryReceipt>;
 offers(positionId:string, amount:string):Promise<Offer[]>;
 saveDocumentDraft(kind:'exit'|'subscription',id:string):Promise<void>;
 resumeDocumentDraft(id:string):Promise<ResumedDocument>;
 renewDocumentDraft(id:string):Promise<ResumedDocument>;
 signExit(offer:Offer,typedName:string,consent:true,onProgress?:(progress:WalletProgress)=>void):Promise<Offer>;
 settleExit(offer:Offer,onProgress?:(progress:WalletProgress)=>void):Promise<Receipt>;
 releaseReservation(digest:Hex):Promise<Receipt>;
 checkEligibility(vehicleId:string):Promise<DemoState>;
 prepareSubscription(vehicleId:string,amount:string):Promise<PreparedSubscription>;
 signSubscription(vehicleId:string,amount:string,prepared:PreparedSubscription,typedName:string,consent:true,onProgress?:(progress:WalletProgress)=>void):Promise<DemoState>;
 fund(vehicleId:string,amount:string,onProgress?:(progress:WalletProgress)=>void):Promise<Receipt>;
 providerAction(vehicleId:string,action:'claim'|'processQueue'|'cancel',requestId?:string):Promise<Receipt>;
 withdraw(vehicleId:string, amount:string):Promise<Receipt>;
 workspaceAction(actionId:string, inputs:Record<string,string>):Promise<Receipt>;
 mintPosition():Promise<Receipt>;
 getTestGas():Promise<Receipt>;
 getTestUsdg():Promise<Receipt>;
}
