import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { privateKeyToAccount } from '../harness/node_modules/viem/_esm/accounts/index.js';
const base='http://127.0.0.1:8791';
const secrets=Object.fromEntries((await readFile(new URL('.dev.vars',import.meta.url),'utf8')).split('\n').filter(Boolean).map(line=>{const i=line.indexOf('=');return [line.slice(0,i),JSON.parse(line.slice(i+1))];}));
const api=async(path,body,headers={})=>{const response=await fetch(base+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...headers},body:body?JSON.stringify(body):undefined});return {status:response.status,body:await response.json()};};
const before=await api('/api/demo/config');assert.ok([200,503].includes(before.status));
assert.equal((await api('/api/demo/admin/import',{})).status,404);
const state=JSON.parse(await readFile(new URL('../scripts/demo/local/public-sepolia-state.json',import.meta.url),'utf8'));
const imported=await api('/api/demo/admin/import',state,{authorization:`Bearer ${secrets.LOCKGATE_IMPORT_TOKEN}`});assert.ok([200,409].includes(imported.status));
assert.equal((await api('/api/demo/admin/import',state,{authorization:`Bearer ${secrets.LOCKGATE_IMPORT_TOKEN}`})).status,409);
const config=await api('/api/demo/config');assert.equal(config.status,200);assert.equal(config.body.chainId,421614);assert.equal(config.body.rpcUrl,'https://openhouse.lockgate.finance/api/demo/rpc/421614');assert.equal(JSON.stringify(config.body).includes('quiknode'),false);
assert.equal((await api('/api/demo/config',undefined,{origin:'https://evil.invalid'})).status,403);
assert.equal((await api('/api/demo/state')).status,401);
assert.equal((await api('/api/demo/rpc/421614',{jsonrpc:'2.0',id:1,method:'eth_sendRawTransaction',params:[]})).status,400);
const rpc=await api('/api/demo/rpc/421614',{jsonrpc:'2.0',id:1,method:'eth_chainId',params:[]});assert.equal(rpc.status,200);assert.equal(rpc.body.result,'0x66eee');
const signer=privateKeyToAccount(`0x${'8'.repeat(64)}`),account=signer.address;
const challenge=await api('/api/demo/challenge',{account,chainId:421614},{origin:'https://openhouse.lockgate.finance'});assert.equal(challenge.status,200);
const auth={account,chainId:421614,...challenge.body,signature:await signer.signMessage({message:challenge.body.message})};
const authenticated=await api('/api/demo/authenticate',auth);assert.equal(authenticated.status,200);assert.match(authenticated.body.token,/^[a-f0-9]{64}$/);
assert.equal((await api('/api/demo/authenticate',auth)).status,401);
const saved=await api('/api/demo/state',undefined,{authorization:`Bearer ${authenticated.body.token}`});assert.equal(saved.status,200);
process.stdout.write(JSON.stringify({passed:true,importStatus:imported.status,checks:['durable import guard','canonical config','private RPC redaction','origin rejection','auth gate','RPC allowlist','wallet signature','nonce replay','authenticated state']})+'\n');
