import { expect, test, type BrowserContext, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { formatUnits, keccak256, parseAbi, parseEventLogs, parseUnits, toHex, type Address, type Hex } from 'viem';
import { assertLocalChain, injectDemoWallet, type WalletProof } from './demo-wallet';
import { captureWidths, copyVideo, evidenceDir, hashFile, prepareProof, saveProof, until } from './demo-proof';

type Manifest={chainId:number;rpcUrl:string;asset:Address;registry:Address;settlement:Address;vaults:{id:string;name:string;firm:string;address:Address;manager:Address}[];originators:{name:string;address:Address}[]};
type Opened={persona:string;page:Page;context:BrowserContext;account:Address;token:()=>string;wallet:Awaited<ReturnType<typeof injectDemoWallet>>};
const tokenAbi=parseAbi(['function balanceOf(address) view returns (uint256)']);
const vaultAbi=parseAbi(['function bookUnits(address) view returns (uint256)','function totalUnits() view returns (uint256)','function availableCash() view returns (uint256)','function queuedUnits(address) view returns (uint256)','function claimable(address) view returns (uint256)','function providerCount() view returns (uint256)','function mandates(address) view returns (uint256 totalLimit,uint256 dealLimit,uint8 routeMask)']);
const registryAbi=parseAbi(['function isActive(address,uint8) view returns (bool)','function holding(bytes32) view returns (address originator,bytes32 ownerIdentity,uint256 remaining,uint256 locked,uint8 routeMask,bool divisible)']);
const eventAbi=parseAbi(['event Settled(bytes32 indexed digest,address indexed investor,uint8 route,uint256 units,uint256 payout,uint256 repayment)','event Repaid(bytes32 indexed digest,address indexed payer,uint256 amount,uint256 remaining)','event HoldingRegistered(bytes32 indexed id,address indexed originator,bytes32 indexed identity,uint256 units)']);
test('four TEST personas complete real local signed-wallet journeys with scoped failures',async({browser})=>{
 test.skip(process.env.LOCKGATE_DEMO_E2E!=='1','Explicit local Anvil + demo API opt in.');
 test.setTimeout(900_000);
 await prepareProof();
 const chain=await assertLocalChain();
 const manifest=JSON.parse(await readFile(resolve('public/demo-contracts.json'),'utf8')) as Manifest;
 expect(manifest.chainId).toBe(421614);
 expect(manifest.rpcUrl).toBe('http://127.0.0.1:8545');
 expect(manifest.vaults).toHaveLength(5);
 expect(manifest.originators).toHaveLength(5);
 const walletProof:WalletProof[]=[],screenshots:unknown[]=[],videos:unknown[]=[],checks:unknown[]=[],contexts:Opened[]=[];
 let phase='chain preflight',failure:string|undefined;
 const api=async(opened:Opened,path:string,body?:unknown)=>{
  const token=opened.token();expect(token).toMatch(/^[0-9a-f]{64}$/);
  return opened.page.request.fetch(`/api/demo/${path}`,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${token}`,...(body===undefined?{}:{'Content-Type':'application/json'})},data:body===undefined?undefined:body});
 };
 const capture=async(opened:Opened,label:string)=>screenshots.push(...await captureWidths(opened.page,label,'workspace'));
 const open=async(persona:string,index:number):Promise<Opened>=>{
  const context=await browser.newContext({baseURL:'http://127.0.0.1:5197',viewport:{width:1440,height:900},recordVideo:{dir:evidenceDir,size:{width:1440,height:900}}});
  context.setDefaultTimeout(20_000);
  const page=await context.newPage();let session='';
  page.on('response',response=>{if(response.url().endsWith('/api/demo/authenticate')&&response.ok())void response.json().then(value=>{session=value.token;}).catch(()=>{});});
  const wallet=await injectDemoWallet(page,index,persona,walletProof);
  const opened={persona,page,context,account:wallet.account.address,token:()=>session,wallet};contexts.push(opened);
  await page.goto('/');
  await page.getByRole('button',{name:/Connect wallet/}).click();
  await expect.poll(()=>session).toMatch(/^[0-9a-f]{64}$/);
  return opened;
 };
 const select=async(opened:Opened,role:'Capital provider'|'Exit investor'|'Originating fund / platform'|'Licensed investment firm')=>{
  const action=opened.page.getByRole('button',{name:new RegExp(`— ${role.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`)});
  if(await action.count())await action.click();
  await expect(opened.page.getByRole('navigation',{name:'Workspace'})).toContainText(role);
 };
 const identity=async(opened:Opened,name:string)=>{
  const state=await (await api(opened,'state')).json();
  if(state.profile.identity)return;
  const start=opened.page.getByRole('button',{name:'Start KYC'});
  await expect(start).toBeVisible();
  await start.click();
  await opened.page.getByRole('radio',{name:new RegExp(name)}).check();
  await opened.page.getByRole('button',{name:'Use selected profile'}).click();
 };
 const receiptDetail=async(hash:Hex)=>{
  const receipt=await chain.getTransactionReceipt({hash});
  const tx=await chain.getTransaction({hash});
  return {hash,from:tx.from,to:tx.to,blockNumber:String(receipt.blockNumber),status:receipt.status,gasUsed:String(receipt.gasUsed),logs:receipt.logs.length};
 };
 try {
  phase='five-by-five chain seed';
  const originators=[] as unknown[],fundedFirms=[] as unknown[];
  for(const org of manifest.originators){
   const active=await chain.readContract({address:manifest.registry,abi:registryAbi,functionName:'isActive',args:[org.address,1]});
   expect(active).toBe(true);originators.push({name:org.name,address:org.address,active});
  }
  for(const firm of manifest.vaults){
   const active=await chain.readContract({address:manifest.registry,abi:registryAbi,functionName:'isActive',args:[firm.manager,2]});
   const providers=await chain.readContract({address:firm.address,abi:vaultAbi,functionName:'providerCount'});
   const cash=await chain.readContract({address:firm.address,abi:vaultAbi,functionName:'availableCash'});
   expect(active).toBe(true);expect(providers).toBe(1n);expect(cash).toBeGreaterThan(0n);
   fundedFirms.push({id:firm.id,name:firm.name,vault:firm.address,manager:firm.manager,active,providers:String(providers),cash:formatUnits(cash,6)});
  }
  checks.push({phase,originators,fundedFirms});
  const seededHoldings=parseEventLogs({abi:eventAbi,eventName:'HoldingRegistered',logs:await chain.getLogs({address:manifest.registry,fromBlock:0n})});
  expect(seededHoldings).toHaveLength(8);
  const alexHoldingId=seededHoldings.find(event=>event.args.identity===keccak256(toHex('TEST-IDENTITY-001')))?.args.id;
  expect(alexHoldingId).toBeDefined();

  phase='wrong owner and empty profile';
  const mismatch=await open('mismatch',3);await select(mismatch,'Exit investor');await identity(mismatch,'Nisha Rao');
  await expect(mismatch.page.getByRole('heading',{name:/couldn’t verify this position/i})).toBeVisible();
  const denied=await api(mismatch,'offers',{positionId:alexHoldingId,amount:'1000'});expect(denied.status()).toBe(403);
  checks.push({phase,offerHttpStatus:denied.status(),response:await denied.json()});
  const empty=await open('empty',4);await select(empty,'Exit investor');await identity(empty,'Elias Haddad');
  await expect(empty.page.getByRole('heading',{name:/No supported positions found/i})).toBeVisible();
  expect((await (await api(empty,'state')).json()).positions).toHaveLength(0);
  checks.push({phase:'empty profile',positions:0});

  phase='capital provider exact subscription';
  const provider=await open('provider',11);await select(provider,'Capital provider');await identity(provider,'Priya Menon');
  await expect(provider.page.getByRole('heading',{name:'Choose your investment vehicle.'})).toBeVisible();
  const providerBefore=await chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'bookUnits',args:[provider.account]});
  await provider.page.getByRole('button',{name:'Demo',exact:true}).click();
  const testBalance=await chain.readContract({address:manifest.asset,abi:tokenAbi,functionName:'balanceOf',args:[provider.account]});
  if(testBalance<parseUnits('1000',6))await provider.page.getByRole('dialog').getByRole('button',{name:'Get test USDG'}).click();
  const spendable=await chain.readContract({address:manifest.asset,abi:tokenAbi,functionName:'balanceOf',args:[provider.account]});
  expect(spendable).toBeGreaterThanOrEqual(parseUnits('1000',6));
  await expect(provider.page.getByRole('dialog')).toContainText(`${formatUnits(spendable,6)} USDG`);
  await provider.page.getByRole('button',{name:'Close Demo'}).click();
  await provider.page.getByRole('button',{name:'View vehicle'}).first().click();
  await expect(provider.page.getByRole('heading',{name:'Your vehicle interest.'})).toBeVisible();
  await provider.page.getByRole('button',{name:'Add capital'}).click();
  await expect(provider.page.getByText('Eligible for this vehicle')).toBeVisible();
  const eligibility=await api(provider,'eligibility',{vehicleId:manifest.vaults[0].id});expect(eligibility.status()).toBe(200);
  const prior=(await (await api(provider,'state')).json()).vehicles[0].agreement?.amount;
  const fundingAmount=prior?String(Number(prior)+100):'1000';
  expect(spendable).toBeGreaterThanOrEqual(parseUnits(fundingAmount,6));
  await provider.page.getByRole('textbox',{name:'Subscription amount'}).fill(fundingAmount);
  await provider.page.getByRole('button',{name:'Review terms'}).click();
  await provider.page.getByRole('checkbox',{name:/I accept this agreement/}).check();
  provider.wallet.state.rejectNext=true;
  await provider.page.getByRole('button',{name:'Sign subscription'}).click();
  await expect(provider.page.getByRole('alert')).toContainText(/rejected/i);
  await provider.page.getByRole('button',{name:'Sign subscription'}).click();
  const fundLabel=`Approve & fund ${new Intl.NumberFormat('en-US').format(Number(fundingAmount))} USDG`;
  await expect(provider.page.getByRole('button',{name:fundLabel})).toBeEnabled();
  await provider.page.reload();
  await provider.page.getByRole('button',{name:'Sign in to Lockgate'}).click();
  await expect(provider.page.getByRole('heading',{name:'Choose your investment vehicle.'})).toBeVisible();
  await provider.page.getByRole('button',{name:'View vehicle'}).first().click();
  await provider.page.getByRole('button',{name:'Add capital'}).click();
  await provider.page.getByRole('textbox',{name:'Subscription amount'}).fill(fundingAmount);
  await provider.page.getByRole('button',{name:'Review terms'}).click();
  await provider.page.getByRole('checkbox',{name:/I accept this agreement/}).check();
  const fundButton=provider.page.getByRole('button',{name:fundLabel});
  await expect(fundButton).toBeEnabled();
  await fundButton.click();
  await expect(provider.page.getByRole('heading',{name:'Your vehicle interest.'})).toBeVisible();
  const providerAfter=await until(()=>chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'bookUnits',args:[provider.account]}),value=>value>providerBefore);
  expect(providerAfter-providerBefore).toBeGreaterThan(0n);
  await provider.page.getByRole('button',{name:'Add capital'}).click();
  await provider.page.getByRole('textbox',{name:'Subscription amount'}).fill(fundingAmount);
  await provider.page.getByRole('button',{name:'Review terms'}).click();
  await provider.page.getByRole('checkbox',{name:/I accept this agreement/}).check();
  await expect(provider.page.getByRole('button',{name:'Sign subscription'})).toBeVisible();
  await provider.page.getByRole('button',{name:'Back'}).click();
  await provider.page.getByRole('button',{name:'View vehicle'}).first().click();
  checks.push({phase,amount:fundingAmount,reloadResumedFunding:true,fundedAmountRequiresNewSignature:true,bookUnitsBefore:String(providerBefore),bookUnitsAfter:String(providerAfter),eligibilityHttpStatus:eligibility.status()});
  await capture(provider,'provider');

  phase='investor quote and purchase';
  const investor=await open('investor',2);await select(investor,'Exit investor');await identity(investor,'Alex Morgan');
  await expect(investor.page.getByRole('heading',{name:'Your positions.'})).toBeVisible();
  const balanceBefore=await chain.readContract({address:manifest.asset,abi:tokenAbi,functionName:'balanceOf',args:[investor.account]});
  const holdingBefore=await chain.readContract({address:manifest.registry,abi:registryAbi,functionName:'holding',args:[alexHoldingId!]});
  await investor.page.getByRole('button',{name:'Explore an exit'}).first().click();
  await investor.page.getByRole('textbox',{name:'Exit amount'}).fill('40000');
  await investor.page.getByRole('button',{name:'See eligible offers'}).click();
  await expect(investor.page.getByRole('heading',{name:'Compare your net payout.'})).toBeVisible();
  const offerCount=await investor.page.getByRole('button',{name:/Review offer/}).count();expect(offerCount).toBe(5);
  await investor.page.getByRole('button',{name:/Review offer/}).first().click();
  await investor.page.getByRole('checkbox',{name:/I have read this exact agreement/}).check();
  await investor.page.getByRole('button',{name:'Sign agreement'}).click();
  await expect(investor.page.getByRole('button',{name:'Confirm wallet settlement'})).toBeEnabled();
  await investor.page.getByRole('button',{name:'Confirm wallet settlement'}).click();
  await expect(investor.page.getByRole('heading',{name:'Your exit receipt.'})).toBeVisible();
  const balanceAfter=await chain.readContract({address:manifest.asset,abi:tokenAbi,functionName:'balanceOf',args:[investor.account]});
  const holdingAfter=await chain.readContract({address:manifest.registry,abi:registryAbi,functionName:'holding',args:[alexHoldingId!]});
  expect(balanceAfter-balanceBefore).toBe(parseUnits('39200',6));
  expect(holdingBefore[2]-holdingAfter[2]).toBe(parseUnits('40000',6));
  expect(holdingAfter[2]).toBe(parseUnits('60000',6));
  checks.push({phase,offers:offerCount,balanceBefore:formatUnits(balanceBefore,6),balanceAfter:formatUnits(balanceAfter,6),holdingBefore:formatUnits(holdingBefore[2],6),holdingAfter:formatUnits(holdingAfter[2],6)});
  await capture(investor,'investor');

  phase='investor financing route and originator debt';
  await investor.page.getByRole('button',{name:'Return to positions'}).click();
  await investor.page.getByRole('button',{name:'Explore an exit'}).first().click();
  await investor.page.getByRole('textbox',{name:'Exit amount'}).fill('20000');
  await investor.page.getByRole('button',{name:'See eligible offers'}).click();
  await expect(investor.page.getByRole('button',{name:/Review offer/})).toHaveCount(5);
  await investor.page.getByRole('button',{name:/Review offer/}).nth(1).click();
  await expect(investor.page.getByRole('heading',{name:'Review your exit.'})).toBeVisible();
  await expect(investor.page.getByText('Borrower-financed discharge')).toBeVisible();
  await investor.page.getByRole('checkbox',{name:/I have read this exact agreement/}).check();
  await investor.page.getByRole('button',{name:'Sign agreement'}).click();
  await investor.page.getByRole('button',{name:'Confirm wallet settlement'}).click();
  await expect(investor.page.getByRole('heading',{name:'Your exit receipt.'})).toBeVisible();
  const financeTx=walletProof.filter(p=>p.persona==='investor'&&p.transactionHash).at(-1)?.transactionHash;
  expect(financeTx).toBeDefined();
  const financeLogs=parseEventLogs({abi:eventAbi,eventName:'Settled',logs:(await chain.getTransactionReceipt({hash:financeTx!})).logs});
  expect(financeLogs).toHaveLength(1);expect(financeLogs[0].args.route).toBe(2);
  const financeDigest=financeLogs[0].args.digest,repayment=financeLogs[0].args.repayment;
  checks.push({phase,digest:financeDigest,payout:formatUnits(financeLogs[0].args.payout,6),repayment:formatUnits(repayment,6)});

  phase='provider withdrawal and queue';
  await provider.page.getByRole('textbox',{name:'Amount in USDG'}).fill('100');
  await provider.page.getByRole('button',{name:'Request withdrawal'}).click();
  await expect(provider.page.getByText('Withdrawal received')).toBeVisible();
  await provider.page.getByRole('textbox',{name:'Amount in USDG'}).fill('470000');
  await provider.page.getByRole('button',{name:'Request withdrawal'}).click();
  await expect(provider.page.getByText('Withdrawal requested')).toBeVisible();
  const queued=await until(()=>chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'queuedUnits',args:[provider.account]}),value=>value>0n);expect(queued).toBeGreaterThan(0n);
  checks.push({phase,queuedUnits:String(queued)});

  phase='organization wallet dashboards';
  const originator=await open('originator',1);await select(originator,'Originating fund / platform');
  await expect(originator.page.getByRole('heading',{name:'Originator workspace'})).toBeVisible();
  await originator.page.getByRole('button',{name:'Register TEST holding'}).click();
  await originator.page.getByRole('combobox',{name:'TEST profile'}).click();await originator.page.getByRole('option',{name:/Lucas Chen/}).click();
  await originator.page.getByLabel('Units').fill('500');
  await originator.page.getByRole('combobox',{name:'Permitted routes'}).click();await originator.page.getByRole('option',{name:'Both permitted routes'}).click();
  await originator.page.getByRole('combobox',{name:'Exit policy'}).click();await originator.page.getByRole('option',{name:'Partial exits permitted'}).click();
  await originator.page.getByRole('button',{name:'Review action'}).click();
  await originator.page.getByRole('button',{name:'Confirm in wallet'}).click();
  await expect(originator.page.getByRole('heading',{name:'Originator workspace'})).toBeVisible();
  const registerTx=await until(async()=>walletProof.filter(p=>p.persona==='originator'&&p.transactionHash).at(-1)?.transactionHash,Boolean);
  const registered=parseEventLogs({abi:eventAbi,eventName:'HoldingRegistered',logs:(await chain.getTransactionReceipt({hash:registerTx!})).logs});
  expect(registered).toHaveLength(1);
  expect((await chain.readContract({address:manifest.registry,abi:registryAbi,functionName:'holding',args:[registered[0].args.id]}))[2]).toBe(parseUnits('500',6));
  await originator.page.getByRole('button',{name:'Repay a financed exit'}).click();
  await originator.page.getByRole('combobox',{name:'Exit obligation'}).click();await originator.page.getByRole('option',{name:/Finance/}).click();
  await originator.page.getByRole('button',{name:'Review action'}).click();
  const originatorBalanceBefore=await chain.readContract({address:manifest.asset,abi:tokenAbi,functionName:'balanceOf',args:[originator.account]});
  await originator.page.getByRole('button',{name:'Confirm in wallet'}).click();
  await expect(originator.page.getByRole('heading',{name:'Originator workspace'})).toBeVisible();
  const originatorBalanceAfter=await until(()=>chain.readContract({address:manifest.asset,abi:tokenAbi,functionName:'balanceOf',args:[originator.account]}),value=>originatorBalanceBefore-value===repayment);
  expect(originatorBalanceBefore-originatorBalanceAfter).toBe(repayment);
  const repayTx=walletProof.filter(p=>p.persona==='originator'&&p.transactionHash).at(-1)?.transactionHash;
  const repaid=parseEventLogs({abi:eventAbi,eventName:'Repaid',logs:(await chain.getTransactionReceipt({hash:repayTx!})).logs});
  expect(repaid).toHaveLength(1);expect(repaid[0].args.remaining).toBe(0n);
  checks.push({phase,registeredHolding:registered[0].args.id,repayDigest:repaid[0].args.digest,originatorBalanceBefore:formatUnits(originatorBalanceBefore,6),originatorBalanceAfter:formatUnits(originatorBalanceAfter,6)});
  await capture(originator,'originator');
  const manager=await open('manager',6);await select(manager,'Licensed investment firm');
  await expect(manager.page.getByRole('heading',{name:'Investment firm workspace'})).toBeVisible();
  await manager.page.getByRole('button',{name:'Set risk mandate'}).click();
  await manager.page.getByRole('combobox',{name:'Originator'}).click();await manager.page.getByRole('option',{name:'Alder Credit Platform'}).click();
  await manager.page.getByLabel('Maximum exposure (% of NAV)').fill('20');
  await manager.page.getByLabel('Per-deal limit (test USDG)').fill('10000');
  await manager.page.getByRole('combobox',{name:'Permitted routes'}).click();await manager.page.getByRole('option',{name:'Both permitted routes'}).click();
  await manager.page.getByRole('button',{name:'Review action'}).click();
  await manager.page.getByRole('button',{name:'Confirm in wallet'}).click();
  await expect(manager.page.getByRole('heading',{name:'Investment firm workspace'})).toBeVisible();
  const mandate=await until(()=>chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'mandates',args:[manifest.originators[0].address]}),value=>value[1]===parseUnits('10000',6));
  expect(mandate[1]).toBe(parseUnits('10000',6));expect(mandate[2]).toBe(3);
  await manager.page.getByRole('button',{name:'Process withdrawal queue'}).click();
  await manager.page.getByLabel('Maximum requests (1–50)').fill('1');
  await manager.page.getByRole('button',{name:'Review action'}).click();
  await manager.page.getByRole('button',{name:'Confirm in wallet'}).click();
  await expect(manager.page.getByRole('heading',{name:'Investment firm workspace'})).toBeVisible();
  const afterQueue=await until(()=>chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'queuedUnits',args:[provider.account]}),value=>value<queued);
  expect(afterQueue).toBeLessThan(queued);
  expect(afterQueue).toBeGreaterThan(0n);
  const cashClaim=await chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'claimable',args:[provider.account]});
  expect(cashClaim).toBeGreaterThan(0n);
  const otherQueue=await chain.readContract({address:manifest.vaults[1].address,abi:vaultAbi,functionName:'queuedUnits',args:[provider.account]});
  expect(otherQueue).toBe(0n);
  checks.push({phase:'firm mandate and queue',mandateLimit:String(mandate[0]),dealLimit:String(mandate[1]),queueBefore:String(queued),queueAfter:String(afterQueue),claimable:String(cashClaim),otherVehicleQueue:String(otherQueue)});
  await capture(manager,'manager');

  phase='provider claim and cancel remaining queue';
  await provider.page.getByRole('button',{name:'Refresh workspace'}).click();
  await expect(provider.page.getByRole('button',{name:/Claim [\d,.]+ USDG/})).toBeEnabled();
  const beforeClaim=await chain.readContract({address:manifest.asset,abi:tokenAbi,functionName:'balanceOf',args:[provider.account]});
  await provider.page.getByRole('button',{name:/Claim [\d,.]+ USDG/}).click();
  const afterClaim=await until(()=>chain.readContract({address:manifest.asset,abi:tokenAbi,functionName:'balanceOf',args:[provider.account]}),value=>value-beforeClaim===cashClaim);
  expect(afterClaim-beforeClaim).toBe(cashClaim);
  const bookBeforeCancel=await chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'bookUnits',args:[provider.account]});
  await provider.page.getByRole('button',{name:'Cancel unfilled'}).click();
  const finalQueued=await until(()=>chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'queuedUnits',args:[provider.account]}),value=>value===0n);
  const bookAfterCancel=await chain.readContract({address:manifest.vaults[0].address,abi:vaultAbi,functionName:'bookUnits',args:[provider.account]});
  expect(finalQueued).toBe(0n);expect(bookAfterCancel).toBe(bookBeforeCancel);
  checks.push({phase,balanceBefore:formatUnits(beforeClaim,6),balanceAfter:formatUnits(afterClaim,6),claimed:formatUnits(cashClaim,6),bookAfterCancel:String(bookAfterCancel),queuedAfterCancel:String(finalQueued)});

  phase='forged session, network, account and reload';
  const badRole=await api(provider,'role',{role:'manager-admin'});expect(badRole.status()).toBe(400);
  const roleSwitch=await api(provider,'role',{role:'manager'});expect(roleSwitch.status()).toBe(200);
  const forgedManager=await api(provider,'workspace-action',{actionId:'manager.set-mandate',inputs:{originatorAddress:manifest.originators[0].address,exposurePercent:'20',dealLimit:'10000',routeMask:'3'}});expect(forgedManager.status()).toBe(403);
  const forgedIdentity=await api(originator,'identity',{profileId:'alex-morgan'});expect(forgedIdentity.status()).toBe(403);
  const noAuth=await provider.page.request.get('/api/demo/state');expect(noAuth.status()).toBe(401);
  const ownReceipt=(await (await api(investor,'state')).json()).receipts.find((r:{hash?:Hex})=>r.hash);
  const crossReceipt=await api(provider,'receipts',{hash:ownReceipt.hash,title:'Forged receipt'});expect(crossReceipt.status()).toBe(403);
  const txCount=walletProof.filter(p=>p.method==='eth_sendTransaction').length;
  await provider.wallet.setWallet({chainId:1});
  await expect(provider.page.getByRole('heading',{name:'This deployment is unavailable.'})).toBeVisible();
  await provider.wallet.setWallet({chainId:421614});
  await provider.wallet.setWallet({selected:originator.account});
  await expect(provider.page.getByRole('button',{name:'Sign in to Lockgate'})).toBeVisible();
  await expect(provider.page.getByText('Personal ledger')).toHaveCount(0);
  expect(walletProof.filter(p=>p.method==='eth_sendTransaction')).toHaveLength(txCount);
  await investor.page.reload();
  await investor.page.getByRole('button',{name:'Sign in to Lockgate'}).click();
  await expect(investor.page.getByRole('heading',{name:'Your positions.'})).toBeVisible();
  checks.push({phase,badRole:badRole.status(),forgedManager:forgedManager.status(),forgedIdentity:forgedIdentity.status(),noAuth:noAuth.status(),crossReceipt:crossReceipt.status(),walletTransactionsAfterChange:txCount});
 } catch(error) {failure=error instanceof Error?error.stack??error.message:String(error);throw error;}
 finally {
  phase=failure?phase:'complete';
  for(const opened of contexts){
   try{const video=opened.page.video();await opened.context.close();const source=await video?.path();if(source)videos.push(await copyVideo(source,opened.persona));}
   catch(error){videos.push({persona:opened.persona,error:String(error)});}
  }
  const transactionProof=await Promise.all(walletProof.filter(item=>item.transactionHash).map(item=>receiptDetail(item.transactionHash!)));
  const sourceFiles=['public/demo-contracts.json','test/demo-wallet.ts','test/demo-signed-flow.spec.ts','src/demo/DemoApp.tsx','src/services/demo-gateway.ts','../harness/src/demo/server.ts','../contracts/src/demo/DemoSettlement.sol'];
  const sourceHashes=Object.fromEntries(await Promise.all(sourceFiles.map(async file=>[file,await hashFile(resolve(file))])));
  await saveProof('evidence.json',{environment:'LOCAL ANVIL TEST ONLY; six-decimal MockUSDG; no public Paxos or Sepolia receipt',chainId:421614,blockNumber:String(await chain.getBlockNumber()),phase,failure,sourceHashes,checks,transactions:transactionProof,walletProof,screenshots,videos});
 }
});
