import {afterEach,describe,expect,it,vi} from 'vitest';
import {assertWalletChain,switchNetwork} from '../src/chain/wallet';
import {getNetwork,NETWORKS,SUPPORTED_NETWORKS,type SupportedNetworkId} from '../src/chain/networks';
afterEach(()=>vi.unstubAllGlobals());
function provider(){const request=vi.fn();vi.stubGlobal('window',{ethereum:{request}});return request;}
describe('supported wallet networks',()=>{
 it('lists both networks and marks mainnet contracts unavailable',()=>{expect(SUPPORTED_NETWORKS.map(n=>n.id)).toEqual([421614,42161]);expect(NETWORKS[42161].contractsAvailable).toBe(false);expect(NETWORKS[421614].contractsAvailable).toBe(true);expect(()=>getNetwork(1)).toThrow('Choose');});
 it.each([421614,42161] as const)('switches to %i and verifies the wallet result',async id=>{const request=provider();const hex=`0x${id.toString(16)}`;request.mockResolvedValueOnce(null).mockResolvedValueOnce(hex);await switchNetwork(id);expect(request.mock.calls).toEqual([[{method:'wallet_switchEthereumChain',params:[{chainId:hex}]}],[{method:'eth_chainId'}]]);});
 it('defaults to Arbitrum Sepolia for existing callers',async()=>{const request=provider();request.mockResolvedValueOnce(null).mockResolvedValueOnce('0x66eee');await switchNetwork();expect(request.mock.calls[0][0].params).toEqual([{chainId:'0x66eee'}]);});
 it.each([421614,42161] as const)('adds missing network %i then switches and verifies',async id=>{const request=provider();const network=getNetwork(id);const hex=`0x${id.toString(16)}`;request.mockRejectedValueOnce({code:4902}).mockResolvedValueOnce(null).mockResolvedValueOnce(null).mockResolvedValueOnce(hex);await switchNetwork(id);expect(request.mock.calls[1][0]).toEqual({method:'wallet_addEthereumChain',params:[{chainId:hex,chainName:network.name,nativeCurrency:network.chain.nativeCurrency,rpcUrls:[network.rpcUrl],blockExplorerUrls:[network.explorerUrl]}]});expect(request.mock.calls[2][0].method).toBe('wallet_switchEthereumChain');expect(request.mock.calls[3][0].method).toBe('eth_chainId');});
 it.each([421614,42161] as const)('rejects wallet mismatch for %i even after a successful switch response',async id=>{const request=provider();request.mockResolvedValueOnce(null).mockResolvedValueOnce(id===421614?'0xa4b1':'0x66eee');await expect(switchNetwork(id)).rejects.toThrow('did not switch');});
 it('rejects a wallet that remains on the old network after add-and-switch',async()=>{const request=provider();request.mockRejectedValueOnce({code:4902}).mockResolvedValueOnce(null).mockResolvedValueOnce(null).mockResolvedValueOnce('0x66eee');await expect(switchNetwork(42161)).rejects.toThrow('Arbitrum One');});
 it('does not add networks after user rejection',async()=>{const request=provider();request.mockRejectedValueOnce({code:4001,message:'User rejected'});await expect(switchNetwork(42161)).rejects.toMatchObject({code:4001});expect(request).toHaveBeenCalledTimes(1);});
 it('propagates rejection while adding a missing network',async()=>{const request=provider();request.mockRejectedValueOnce({code:4902}).mockRejectedValueOnce({code:4001});await expect(switchNetwork(42161)).rejects.toMatchObject({code:4001});expect(request).toHaveBeenCalledTimes(2);});
 it('propagates rejection of the second switch after adding',async()=>{const request=provider();request.mockRejectedValueOnce({code:4902}).mockResolvedValueOnce(null).mockRejectedValueOnce({code:4001});await expect(switchNetwork(42161)).rejects.toMatchObject({code:4001});expect(request).toHaveBeenCalledTimes(3);});
 it('validates network selection before making wallet requests',async()=>{const request=provider();await expect(switchNetwork(1 as SupportedNetworkId)).rejects.toThrow('Choose');expect(request).not.toHaveBeenCalled();});
 it('keeps contract-signing restricted to the Sepolia deployment',()=>{expect(()=>assertWalletChain(42161)).toThrow('Sepolia');expect(()=>assertWalletChain(421614)).not.toThrow();});
});
