import {describe,expect,it} from 'vitest';
import {judgeReadiness} from '../src/chain/readiness';
import {previewSnapshot} from '../src/ui/preview';
import type {Address} from 'viem';
const owner:Address='0x1111111111111111111111111111111111111111';
const outsider:Address='0x2222222222222222222222222222222222222222';
function snapshot(){const s=previewSnapshot();s.mode='live';s.account=owner;s.platforms[0].issuer=owner;s.creditLine.owner=owner;s.platforms[0].requests[0].owner=owner;s.creditLine.advances=s.creditLine.advances.map(a=>({...a,to:outsider}));return s;}
const check=(r:ReturnType<typeof judgeReadiness>,id:string)=>r.checks.find(c=>c.id===id)!;
describe('Open House actual readiness',()=>{
 it('never presents preview conditions as transaction-ready or historical evidence',()=>{const r=judgeReadiness(previewSnapshot(),owner,421614);expect(r.canFund).toBe(false);expect(r.exitPreconditionsMet).toBe(false);expect(r.canProcessWindow).toBe(false);expect(r.ownAdvances).toEqual([]);expect(r.historicalAdvances).toEqual([]);});
 it('does not infer readiness from no snapshot or disconnected balances',()=>{const empty=judgeReadiness(null);expect(check(empty,'mode').status).toBe('unknown');expect(check(empty,'mode').detail).not.toContain('Preview');expect(empty.canFund).toBe(false);expect(check(empty,'position').status).not.toBe('ready');const s=snapshot();s.account=undefined;expect(judgeReadiness(s).exitPreconditionsMet).toBe(false);});
 it('requires matching wallet data and the actual Sepolia network',()=>{const s=snapshot();expect(judgeReadiness(s,owner).exitPreconditionsMet).toBe(false);expect(judgeReadiness(s,owner,42161).exitPreconditionsMet).toBe(false);const stale=judgeReadiness(s,outsider,421614);expect(stale.canFund).toBe(false);expect(check(stale,'snapshot').status).toBe('unknown');expect(stale.ownAdvances).toHaveLength(0);});
 it('separates funding prerequisites from a confirmed live quote',()=>{const r=judgeReadiness(snapshot(),owner,421614);expect(r.canFund).toBe(true);expect(r.exitPreconditionsMet).toBe(true);expect(check(r,'capacity').detail).toContain('actual quote');});
 it('blocks a due window while allowing permissionless settlement to an investor',()=>{const s=snapshot();s.platforms[0].nextWindow=0n;s.platforms[0].issuer=outsider;s.creditLine.owner=outsider;const r=judgeReadiness(s,owner,421614);expect(r.exitPreconditionsMet).toBe(false);expect(r.canProcessWindow).toBe(true);expect(r.isIssuer).toBe(false);expect(r.isOperator).toBe(false);expect(check(r,'window').status).toBe('blocked');});
 it('reflects paused, empty, unregistered and exhausted credit conditions',()=>{for(const change of [(s:ReturnType<typeof snapshot>)=>{s.creditLine.paused=true;},(s:ReturnType<typeof snapshot>)=>{s.creditLine.capital=0n;},(s:ReturnType<typeof snapshot>)=>{s.platforms[0].exposure=s.platforms[0].limit;},(s:ReturnType<typeof snapshot>)=>{s.platforms[0].registered=false;}]){const s=snapshot();change(s);expect(judgeReadiness(s,owner,421614).exitPreconditionsMet).toBe(false);}});
 it('does not mark a position ready because some other wallet has historical advances',()=>{const s=snapshot();s.platforms[0].holding=0n;s.platforms[0].requests=[];const r=judgeReadiness(s,owner,421614);expect(check(r,'position').status).toBe('blocked');expect(r.ownAdvances).toHaveLength(0);expect(r.historicalAdvances.length).toBeGreaterThan(0);});
 it('denies issuer-blocked new deposits without inventing a redemption ban on existing shares',()=>{const s=snapshot();s.platforms[0].blocked=true;let r=judgeReadiness(s,owner,421614);expect(r.canFund).toBe(false);expect(r.exitPreconditionsMet).toBe(true);s.platforms[0].holding=0n;s.platforms[0].requests=[];r=judgeReadiness(s,owner,421614);expect(check(r,'eligibility').status).toBe('blocked');});
 it('gating blocks exits even though deposits remain possible in the actual contract',()=>{const s=snapshot();s.platforms[0].gated=true;const r=judgeReadiness(s,owner,421614);expect(r.canFund).toBe(true);expect(r.exitPreconditionsMet).toBe(false);});
 it('does not trust role display flags as issuer or operator permissions',()=>{const s=snapshot();s.platforms[0].issuer=outsider;s.creditLine.owner=outsider;s.roles.operator=true;s.roles.issuerPlatforms=[s.platforms[0].address];const r=judgeReadiness(s,owner,421614);expect(r.isIssuer).toBe(false);expect(r.isOperator).toBe(false);});
 it('requires tokens only for funding, not an existing funded position',()=>{const s=snapshot();s.usdgBalance=0n;const r=judgeReadiness(s,owner,421614);expect(r.canFund).toBe(false);expect(r.exitPreconditionsMet).toBe(true);});
 it('selects a future platform when the old default has no owned position',()=>{const s=snapshot();s.platforms[0].nextWindow=0n;s.platforms[0].holding=0n;s.platforms[0].requests=[];s.platforms.push({...s.platforms[0],address:outsider,name:'Fresh platform',nextWindow:BigInt(Math.floor(Date.now()/1000))+600n});expect(judgeReadiness(s,owner,421614).platform?.address).toBe(outsider);});
 it('honors explicit platform selection even if an older platform has owned shares',()=>{const s=snapshot();s.platforms.push({...s.platforms[0],address:outsider,name:'Fresh platform'});expect(judgeReadiness(s,owner,421614,Date.now(),outsider).platform?.address).toBe(outsider);});

});
