import { test, expect } from '@playwright/test';
import { DEPLOYMENT } from '../src/chain/config';
import { creditLineAbi, platformAbi, vaultAbi } from '../src/chain/abi';
import { factoryAbi } from '../src/chain/factory-abi';
import { facilityAbi } from '../src/chain/facility-abi';
import { personas } from './signed-fork';
import { setupSignedFork } from './signed-setup';
import { deploySignedFacility } from './signed-facility';
import { signedProof } from './signed-proof';
test('remaining existing UI actions use signed transactions on local Sepolia fork',async({browser})=>{
  test.skip(process.env.LOCKGATE_SIGNED_FORK_TEST!=='1','Opt in to localhost signed wallet proof.');test.setTimeout(480000);
  const proof=await signedProof(browser,'remaining');const{fork,open,refresh,confirm,fund,capture}=proof;
  let completed=false;const checks:Record<string,unknown>={};
  try{
    const{platform}=await setupSignedFork(fork);const facility=await deploySignedFacility(fork);
    const investor=await open('investor','/#/platform/'+platform);
    await fund(investor,'Fund a position','2');
    await investor.goto('/#/exit/'+platform+'?mode=queue');
    await investor.getByRole('textbox',{name:'Shares to exit'}).fill('0.5');
    await investor.getByRole('button',{name:'Review redemption',exact:true}).click();await confirm(investor);
    await investor.goto('/#/exit/'+platform+'?request=1');await refresh(investor);
    await expect(investor.getByRole('button',{name:'Review early exit'})).toBeEnabled({timeout:30000});
    await investor.getByRole('button',{name:'Review early exit'}).click();await confirm(investor);
    const request=await fork.client.readContract({address:platform,abi:platformAbi,functionName:'getRequest',args:[1n]});
    expect(request.status).toBe(1);checks.queuedEarlyExit=request;
    const advanceId=request.advanceId;
    await investor.goto('/#/advance/'+advanceId);await refresh(investor);
    await expect(investor.getByRole('heading',{name:'Advance #'+advanceId,exact:true})).toBeVisible();
    await capture(investor,'queued-early-exit-funded');
    const partner=await open('partner','/#/capital');
    await partner.getByRole('button',{name:'Pause vault',exact:true}).click();await confirm(partner);
    expect(await fork.client.readContract({address:DEPLOYMENT.vaultA,abi:vaultAbi,functionName:'paused'})).toBe(true);
    await partner.getByRole('button',{name:'Unpause vault',exact:true}).click();await confirm(partner);
    expect(await fork.client.readContract({address:DEPLOYMENT.vaultA,abi:vaultAbi,functionName:'paused'})).toBe(false);
    await partner.getByLabel('Platform address',{exact:true}).fill(platform);
    await partner.getByLabel('Limit · USDG',{exact:true}).fill('0');
    await partner.getByRole('combobox',{name:'Platform permission'}).click();
    await partner.getByRole('option',{name:'Not approved',exact:true}).click();
    await partner.getByRole('button',{name:'Review platform config'}).click();await confirm(partner);
    const revoked=await fork.client.readContract({address:DEPLOYMENT.vaultA,abi:vaultAbi,functionName:'platformConfig',args:[platform]});
    expect(revoked.approved).toBe(false);expect(revoked.limit).toBe(0n);checks.platformRevoked=revoked;
    await partner.getByLabel('Limit · USDG',{exact:true}).fill('10');
    await partner.getByRole('combobox',{name:'Platform permission'}).click();
    await partner.getByRole('option',{name:'Approved',exact:true}).click();
    await partner.getByRole('button',{name:'Review platform config'}).click();await confirm(partner);
    expect((await fork.client.readContract({address:DEPLOYMENT.vaultA,abi:vaultAbi,functionName:'platformConfig',args:[platform]})).approved).toBe(true);
    await capture(partner,'partner-governance-restored');
    await partner.getByRole('textbox',{name:'Facility lender wallet'}).fill(personas.partner.address);
    await partner.getByRole('button',{name:'Review lender access'}).click();await confirm(partner);
    await partner.getByRole('combobox',{name:'Facility lender permission'}).click();
    await partner.getByRole('option',{name:'Not approved',exact:true}).click();
    await partner.getByRole('button',{name:'Review lender access'}).click();await confirm(partner);
    expect(await fork.client.readContract({address:facility,abi:facilityAbi,functionName:'approvedLender',args:[personas.partner.address]})).toBe(false);
    const senior=partner.locator('.funding-form').filter({has:partner.getByRole('textbox',{name:'Deposit senior capital amount'})});
    await expect(senior.getByRole('button',{name:'Review',exact:true})).toBeDisabled();checks.revokedLenderDepositDenied=true;
    await partner.getByRole('combobox',{name:'Facility lender permission'}).click();
    await partner.getByRole('option',{name:'Approved',exact:true}).click();
    await partner.getByRole('button',{name:'Review lender access'}).click();await confirm(partner);
    await fund(partner,'Deposit senior capital','0.1');
    await partner.getByRole('combobox',{name:'Capital tranche'}).click();await partner.getByRole('option',{name:'Junior',exact:true}).click();
    await fund(partner,'Deposit junior capital','0.04');
    const operator=await open('operator','/#/capital');await fund(operator,'Draw facility capital','0.12');
    const advance=await fork.client.readContract({address:DEPLOYMENT.creditLine,abi:creditLineAbi,functionName:'getAdvance',args:[advanceId]});
    const grace=await fork.client.readContract({address:DEPLOYMENT.creditLine,abi:creditLineAbi,functionName:'graceOf',args:[advanceId]});
    await fork.rpc('evm_setNextBlockTimestamp',[Number(advance.dueAt+grace+1n)]);await fork.rpc('evm_mine');
    await operator.clock.setSystemTime(Number((await fork.client.getBlock()).timestamp)*1000);
    await operator.goto('/#/advance/'+advanceId);await refresh(operator);
    await expect(operator.getByRole('heading',{name:'Advance #'+advanceId,exact:true})).toBeVisible();
    await operator.getByRole('button',{name:'Mark late & apply reserve'}).click();await confirm(operator);
    expect(await fork.client.readContract({address:DEPLOYMENT.creditLine,abi:creditLineAbi,functionName:'remainingOf',args:[advanceId]})).toBe(0n);
    expect((await fork.client.readContract({address:DEPLOYMENT.creditLine,abi:creditLineAbi,functionName:'getAdvance',args:[advanceId]})).status).toBe(2);
    await refresh(operator);await expect(operator.getByText('Reserve recovery',{exact:true})).toBeVisible();await capture(operator,'own-book-reserve-recovered');
    checks.ownBookRecovered=await fork.client.readContract({address:DEPLOYMENT.creditLine,abi:creditLineAbi,functionName:'recoveredOf',args:[advanceId]});
    await operator.goto('/#/capital');await operator.getByRole('button',{name:'Update facility health'}).click();await confirm(operator);
    await operator.getByRole('button',{name:'Recognize loss'}).click();await confirm(operator);
    checks.facilityLoss=await fork.client.readContract({address:facility,abi:facilityAbi,functionName:'accounting'});
    expect((checks.facilityLoss as {recovery:boolean}).recovery).toBe(true);
    await partner.goto('/#/capital');await refresh(partner);
    await partner.getByRole('combobox',{name:'Capital tranche'}).click();await partner.getByRole('option',{name:'Junior',exact:true}).click();
    const junior=partner.locator('.funding-form').filter({has:partner.getByRole('textbox',{name:'Deposit junior capital amount'})});
    await expect(junior.getByRole('button',{name:'Review',exact:true})).toBeDisabled();checks.juniorRecapDenied=true;
    await partner.getByRole('combobox',{name:'Capital tranche'}).click();await partner.getByRole('option',{name:'Senior',exact:true}).click();
    await fund(partner,'Deposit senior capital','0.05');checks.facilityAfterRecap=await fork.client.readContract({address:facility,abi:facilityAbi,functionName:'accounting'});
    expect((checks.facilityAfterRecap as {seniorPrincipal:bigint}).seniorPrincipal).toBe((checks.facilityLoss as {seniorPrincipal:bigint}).seniorPrincipal+50000n);
    await capture(partner,'senior-recovery-recapitalized');
    checks.queueKindsCreated=[];
    for(const [label,kind] of [['Epoch · pro rata',2],['Quarterly · gated window',3]] as const){
      await operator.goto('/#/create');
      await operator.getByRole('textbox',{name:'Platform name',exact:true}).fill('Signed '+label+' registration');
      await operator.getByRole('textbox',{name:/^Issuer wallet/}).fill(personas.issuer.address);
      await operator.getByRole('combobox',{name:'Queue type'}).click();
      await operator.getByRole('option',{name:label,exact:true}).click();
      await operator.getByRole('button',{name:'Review platform creation'}).click();await confirm(operator);
      const funds=await fork.client.readContract({address:DEPLOYMENT.factory,abi:factoryAbi,functionName:'allFunds'});
      const created=funds.at(-1)!;expect(await fork.client.readContract({address:created,abi:platformAbi,functionName:'kind'})).toBe(kind);
      (checks.queueKindsCreated as unknown[]).push({kind,address:created});
    }
    expect(proof.runtimeErrors).toEqual([]);expect(proof.consoleErrors).toEqual([]);completed=true;
  }finally{await proof.finish(completed,checks);}
});
