import { test, expect, type Page, type BrowserContext } from '@playwright/test';
import { mkdir, writeFile, readdir, readFile, rename } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { hashTypedData, keccak256, stringToHex } from 'viem';
import { DEPLOYMENT } from '../src/chain/config';
import { creditLineAbi, platformAbi, tokenAbi, vaultAbi } from '../src/chain/abi';
import { personas, startSignedFork, type Persona } from './signed-fork';
import { setupSignedFork } from './signed-setup';
import { deploySignedFacility } from './signed-facility';
import { facilityFlow, prepareFacilityRecovery, recognizeFacilityLoss } from './signed-facility-flow';
import { signedSource } from './signed-source';
import { issuerEligibility, operatorExtras } from './signed-extra-flow';

test('all personas use locally signed wallet transactions on an isolated Sepolia fork', async ({ browser }) => {
  test.skip(process.env.LOCKGATE_SIGNED_FORK_TEST !== '1', 'Opt in to owned localhost19548 signed-fork verification.');
  test.setTimeout(480_000);
  const artifactDir = resolve(`../docs/proof/wallet/run-${Date.now()}`);
  await mkdir(artifactDir, { recursive: true });
  const fork = await startSignedFork();
  const source=await signedSource();
  const contexts: BrowserContext[] = [];
  const videos: {persona: Persona; page: Page}[] = [];
  const failurePages: unknown[] = [];
  const cleanupErrors:string[]=[];
  const balances: Record<string, unknown> = {};
  const runtimeErrors: string[] = [];
  const consoleErrors:string[]=[];
  const readLatency: Record<string, unknown>[] = [];
  let completed = false;
  const json = (value: unknown) => JSON.stringify(value, (_, v) => typeof v === 'bigint' ? v.toString() : v, 2);
  const capture = async (page: Page, name: string) => {
    const target=await fork.client.getBlockNumber({cacheTime:0});
    await expect.poll(async()=>{
      await expect(page.getByRole('button',{name:'Refresh chain data'})).toBeEnabled({timeout:45000});
      if(name!=='wallet-balances')await page.getByRole('button',{name:'Refresh chain data'}).click();
      await expect(page.getByRole('button',{name:'Refresh chain data'})).toBeEnabled({timeout:45000});
      const text=await page.locator('.data-status').innerText();
      return BigInt(text.match(/Read at block (\d+)/)?.[1]??'0')>=target;
    },{timeout:60000}).toBe(true);
    if(name.startsWith('own-book-advance-')){
      await expect(page.getByRole('heading',{name:/^Advance #\d+$/,exact:true})).toBeVisible();
      await expect(page.locator('.key-values div').filter({has:page.getByText('Remaining owed',{exact:true})}).locator('dd')).toHaveText(name.endsWith('repaid')?'0.00 USDG':'0.50 USDG');
    }
    for (const width of [390, 768, 1440]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.evaluate(()=>window.scrollTo(0,0));
      await page.screenshot({ animations:'disabled', path: resolve(artifactDir, `${name}-${width}.png`), fullPage: name !== 'wallet-balances' });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), `${name} at ${width} no page overflow`).toBe(true);
    }
  };
  const open = async (persona: Persona, route: string) => {
    const context = await browser.newContext({ baseURL: 'http://127.0.0.1:5197', viewport: { width: 1440, height: 1000 }, recordVideo: { dir: artifactDir, size: { width: 1440, height: 1000 } } });
    contexts.push(context);
    const page = await context.newPage();
    videos.push({persona, page});
    context.setDefaultTimeout(30000);
    page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});
    page.on('pageerror', e => { runtimeErrors.push(e.message); void writeFile(resolve(artifactDir,'runtime-errors.json'),json(runtimeErrors)); });
    page.on('framenavigated', frame => { if(frame===page.mainFrame()) void writeFile(resolve(artifactDir,`${persona}-url.txt`),frame.url()); });
    const probe=setInterval(()=>{void page.locator('body').innerText({timeout:1000}).then(text=>writeFile(resolve(artifactDir,`${persona}-state.txt`),text)).catch(()=>{});},5000);
    page.on('close',()=>clearInterval(probe));
    await fork.inject(page, persona);
    await page.clock.setSystemTime(Number((await fork.client.getBlock()).timestamp) * 1000);
    await page.goto(route);
    const connectedAt = Date.now();
    await page.getByRole('button', { name: 'Connect wallet', exact: true }).first().click();
    await expect(page.getByRole('button', { name: 'Connect wallet', exact: true })).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Refresh chain data' })).toBeEnabled({ timeout: 45000 });
    readLatency.push({ persona, connectedSnapshotMs: Date.now() - connectedAt });
    return page;
  };
  const confirm = async (page: Page) => {
    await page.getByRole('dialog').getByRole('button', { name: 'Confirm in wallet' }).click();
    await expect(page.getByRole('heading', { name: 'Transaction confirmed', exact: true })).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Done', exact: true }).click();
  };
  const fund = async (page: Page, title: string, amount: string) => {
    const section = page.locator('.funding-form').filter({ has: page.getByRole('textbox', { name: `${title} amount`, exact: true }) });
    await section.getByRole('textbox').fill(amount);
    await section.getByRole('button', { name: 'Review', exact: true }).click();
    await confirm(page);
  };
  const usd = (persona: Persona) => fork.client.readContract({ address: DEPLOYMENT.usdg, abi: tokenAbi, functionName: 'balanceOf', args: [personas[persona].address] });
  try {
    const { platform, write } = await setupSignedFork(fork);
    const facility = await deploySignedFacility(fork);
    const investor = await open('investor', `/#/platform/${platform}`);
    await investor.getByRole('button', { name: /0x7099/ }).click();
    await expect(investor.getByRole('dialog', { name: 'Your wallet' })).toContainText('USDG');
    await expect(investor.getByRole('dialog', { name: 'Your wallet' })).toContainText('ETH', { timeout: 30000 });
    await capture(investor, 'wallet-balances');
    await investor.getByRole('button', { name: 'Close wallet' }).click();
    await investor.reload();
    await expect(investor.getByRole('button', { name: /0x7099/ })).toBeVisible();
    const deposit = investor.locator('.funding-form').filter({ has: investor.getByRole('textbox', { name: 'Fund a position amount' }) });
    await deposit.getByRole('textbox').fill('4');
    await deposit.getByRole('button', { name: 'Review', exact: true }).click();
    const beforeRejection = fork.receipts.length;
    await fork.setWallet(investor, { chainId: 1 });
    await expect(investor.getByRole('dialog').getByRole('button', { name: 'Confirm in wallet' })).toBeDisabled();
    await fork.setWallet(investor, { chainId: 421614, rejectNext: true });
    await investor.getByRole('dialog').getByRole('button', { name: 'Confirm in wallet' }).click();
    await expect(investor.locator('.tx-progress')).toContainText(/reject/i);
    expect(fork.receipts.length).toBe(beforeRejection);
    await investor.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click();
    balances.investorBefore = await usd('investor');
    await fund(investor, 'Fund a position', '4');
    const share = await fork.client.readContract({ address: platform, abi: platformAbi, functionName: 'share' });
    expect(await fork.client.readContract({ address: share, abi: tokenAbi, functionName: 'balanceOf', args: [personas.investor.address] })).toBe(4n * 10n ** 18n);
    await investor.goto(`/#/exit/${platform}?mode=queue`);
    await investor.getByRole('textbox', { name: 'Shares to exit' }).fill('0.5');
    await investor.getByRole('button', { name: 'Review redemption', exact: true }).click();
    await confirm(investor);
    await investor.goto('/#/positions');
    await investor.getByRole('button', { name: 'Cancel request', exact: true }).click();
    await confirm(investor);
    expect((await fork.client.readContract({ address: platform, abi: platformAbi, functionName: 'getRequest', args: [1n] })).status).toBe(3);
    await investor.goto(`/#/exit/${platform}?mode=queue`);
    await investor.getByRole('textbox', { name: 'Shares to exit' }).fill('0.5');
    await investor.getByRole('button', { name: 'Review redemption', exact: true }).click();
    await confirm(investor);
    await investor.goto(`/#/exit/${platform}`);
    await investor.getByRole('textbox', { name: 'Shares to exit' }).fill('0.5');
    await expect(investor.getByRole('button', { name: 'Review early exit' })).toBeEnabled({timeout:30000});
    balances.beforeEarlyExit = await usd('investor');
    await investor.getByRole('button', { name: 'Review early exit' }).click();
    await confirm(investor);
    balances.afterEarlyExit = await usd('investor');
    expect(balances.afterEarlyExit as bigint).toBeGreaterThan(balances.beforeEarlyExit as bigint);
    const ownAdvanceId=await fork.client.readContract({address:DEPLOYMENT.creditLine,abi:creditLineAbi,functionName:'advanceCount'});
    await investor.goto(`/#/advance/${ownAdvanceId}`); await capture(investor,'own-book-advance-funded');
    await expect(investor.getByRole('heading',{name:`Advance #${ownAdvanceId}`,exact:true})).toBeVisible();
    await expect(investor.locator('.key-values div').filter({has:investor.getByText('Remaining owed',{exact:true})}).locator('dd')).toHaveText('0.50 USDG');
    await investor.goto('/#/positions');
    await capture(investor, 'investor-requests');
    await investor.goto('/#/operations');
    await expect(investor.getByRole('button', { name: 'Pause new advances', exact: true })).toBeDisabled();
    const issuer = await open('issuer', `/#/issuer?platform=${platform}`);
    await issuer.getByLabel('Update NAV · USDG per share').fill('1.1');
    await issuer.getByRole('button', { name: 'Review NAV update' }).click(); await confirm(issuer);
    expect(await fork.client.readContract({ address: platform, abi: platformAbi, functionName: 'nav' })).toBe(1_100_000n);
    await issuer.getByRole('button', { name: 'Gate new requests' }).click(); await confirm(issuer);
    expect(await fork.client.readContract({ address: platform, abi: platformAbi, functionName: 'gated' })).toBe(true);
    await issuer.getByRole('button', { name: 'Remove gate' }).click(); await confirm(issuer);
    await fund(issuer, 'Deposit settlement cash', '2');
    await issuerEligibility(fork, platform, issuer, confirm);
    await capture(issuer, 'issuer-controls');
    const operator = await open('operator', '/#/operations');
    const capitalBefore = await fork.client.readContract({ address: DEPLOYMENT.creditLine, abi: creditLineAbi, functionName: 'capital' });
    await fund(operator, 'Deposit own-book capital', '2');
    await fund(operator, 'Withdraw capital', '1');
    expect(await fork.client.readContract({ address: DEPLOYMENT.creditLine, abi: creditLineAbi, functionName: 'capital' })).toBe(capitalBefore + 1_000_000n);
    await operator.getByLabel('Utilization cap · bps').fill('8500');
    await operator.getByRole('button', { name: 'Review cap changes' }).click(); await confirm(operator);
    await operator.getByRole('button', { name: 'Pause new advances' }).click(); await confirm(operator);
    await operator.getByRole('button', { name: 'Unpause new advances' }).click(); await confirm(operator);
    await capture(operator, 'operator-controls');
    await operatorExtras(fork, platform, operator, confirm, fund);
    const partner = await open('partner', '/#/capital');
    const idleBefore = await fork.client.readContract({ address: DEPLOYMENT.vaultA, abi: vaultAbi, functionName: 'idle' });
    await fund(partner, 'Deposit partner capital', '3');
    await fund(partner, 'Withdraw idle capital', '1');
    expect(await fork.client.readContract({ address: DEPLOYMENT.vaultA, abi: vaultAbi, functionName: 'idle' })).toBe(idleBefore + 2_000_000n);
    const now = (await fork.client.getBlock()).timestamp;
    await partner.getByLabel('Fee floor · bps').fill('100');
    await partner.getByLabel('Maximum tenor · seconds').fill('86400');
    await partner.getByLabel('Concentration cap · bps').fill('10000');
    await partner.getByLabel('Expiry · Unix seconds').fill(String(now + 86400n));
    await partner.getByRole('button', { name: 'Review mandate', exact: true }).click(); await confirm(partner);
    await partner.getByLabel('Platform address', { exact: true }).fill(platform);
    await partner.getByLabel('Limit · USDG', { exact: true }).fill('10');
    await partner.getByLabel('Reserve requirement · bps').fill('750');
    await partner.getByRole('button', { name: 'Review platform config' }).click(); await confirm(partner);
    await partner.getByRole('combobox', { name: 'Partner reserve platform' }).click();
    await partner.getByRole('option', { name: 'Signed wallet verification', exact: true }).click();
    await partner.getByRole('textbox', { name: 'Partner reserve amount' }).fill('1');
    await partner.getByRole('button', { name: 'Review partner reserve' }).click(); await confirm(partner);
    await capture(partner, 'partner-capital');
    const proposal = { platform, recipient: personas.investor.address, requestId: 99n, navValue: 500_000n, fee: 5_000n, payout: 495_000n, feeBps: 100, dueAt: now + 1000n, expiresAt: now + 500n, nonce: 123456n, quoteId: keccak256(stringToHex('signed fork proof')) };
    const types = { AdvanceProposal: ['platform:address','recipient:address','requestId:uint256','navValue:uint256','fee:uint256','payout:uint256','feeBps:uint16','dueAt:uint64','expiresAt:uint64','nonce:uint256','quoteId:bytes32'].map(field => { const [name,type] = field.split(':'); return { name, type }; }) };
    const typed = { domain: { name: 'LockgateAdvance', version: '1', chainId: 421614, verifyingContract: DEPLOYMENT.vaultA }, types, primaryType: 'AdvanceProposal', message: proposal } as const;
    const signature = await personas.engine.signTypedData(typed);
    fork.signatures.push({ persona: 'engine', typed, signature, digest: hashTypedData(typed), purpose: 'Actual engine EIP712 signature accepted by deployed vault on local fork' });
    await write('engine', DEPLOYMENT.vaultA, vaultAbi, 'submitProposal', [proposal, signature]);
    await partner.goto('/#/approvals');
    await partner.getByRole('textbox', { name: 'Engine proposal JSON' }).fill(json({ vault: DEPLOYMENT.vaultA, chainId: 421614, proposal }));
    await partner.getByRole('button', { name: 'Verify against contract' }).click();
    await expect(partner.getByRole('button', { name: 'Authorize funding in wallet' })).toBeEnabled();
    const beforePartnerPayout = await usd('investor');
    await partner.getByRole('button', { name: 'Authorize funding in wallet' }).click();
    await expect(partner.getByRole('button', { name: 'Funding confirmed' })).toBeVisible({ timeout: 30000 });
    expect(await usd('investor')).toBe(beforePartnerPayout + proposal.payout);
    expect(await fork.client.readContract({ address: DEPLOYMENT.vaultA, abi: vaultAbi, functionName: 'nonceUsed', args: [proposal.nonce] })).toBe(true);
    await capture(partner, 'partner-approved');
    const partnerAdvanceId = await fork.client.readContract({ address: DEPLOYMENT.vaultA, abi: vaultAbi, functionName: 'advanceCount' });
    await partner.goto('/#/capital');
    await partner.getByRole('button',{name:'Refresh chain data'}).click();
    await expect(partner.getByRole('button',{name:'Refresh chain data'})).toBeEnabled({timeout:45000});
    await partner.getByRole('combobox', { name: 'Partner advance' }).click();
    await partner.getByRole('option', { name: new RegExp(`^Advance #${partnerAdvanceId} ·`) }).click();
    await expect(partner.getByRole('button', { name: 'Mark partner advance late' })).toBeDisabled();
    await partner.getByRole('button', { name: 'Repay partner advance', exact: true }).click(); await confirm(partner);
    expect(await fork.client.readContract({ address: DEPLOYMENT.vaultA, abi: vaultAbi, functionName: 'owedOf', args: [partnerAdvanceId] })).toBe(0n);
    await capture(partner, 'partner-repaid');
    const lateProposal = { ...proposal, nonce: proposal.nonce + 1n, requestId: 100n, quoteId: keccak256(stringToHex('signed fork late proof')) };
    const lateTyped = { ...typed, message: lateProposal };
    const lateSignature = await personas.engine.signTypedData(lateTyped);
    fork.signatures.push({ persona: 'engine', typed: lateTyped, signature: lateSignature, digest: hashTypedData(lateTyped), purpose: 'Actual engine EIP712 late-recovery fixture' });
    await write('engine', DEPLOYMENT.vaultA, vaultAbi, 'submitProposal', [lateProposal, lateSignature]);
    await partner.goto('/#/approvals');
    await partner.getByRole('textbox', { name: 'Engine proposal JSON' }).fill(json({ vault: DEPLOYMENT.vaultA, chainId: 421614, proposal: lateProposal }));
    await partner.getByRole('button', { name: 'Verify against contract' }).click();
    await expect(partner.getByRole('button', { name: 'Authorize funding in wallet' })).toBeEnabled();
    await partner.getByRole('button', { name: 'Authorize funding in wallet' }).click();
    await expect(partner.getByRole('button', { name: 'Funding confirmed' })).toBeVisible({ timeout: 30000 });
    const lateAdvanceId = await fork.client.readContract({ address: DEPLOYMENT.vaultA, abi: vaultAbi, functionName: 'advanceCount' });
    await facilityFlow(fork, facility, partner, operator, fund, confirm, capture);
    await prepareFacilityRecovery(operator, partner, fund);
    const nextWindow = await fork.client.readContract({address:platform,abi:platformAbi,functionName:'nextWindow'});
    const chainNow=(await fork.client.getBlock()).timestamp;
    await fork.rpc('evm_setNextBlockTimestamp', [Number(nextWindow > chainNow ? nextWindow + 1n : chainNow + 1n)]); await fork.rpc('evm_mine');
    await issuer.clock.setSystemTime(Number((await fork.client.getBlock()).timestamp) * 1000);
    await issuer.goto(`/#/platform/${platform}`);
    await issuer.getByRole('button',{name:'Refresh chain data'}).click();
    await expect(issuer.getByRole('button',{name:'Refresh chain data'})).toBeEnabled({timeout:45000});
    await issuer.getByRole('button', { name: 'Process window', exact: true }).click(); await confirm(issuer);
    expect(await fork.client.readContract({ address: platform, abi: platformAbi, functionName: 'lockgateOwed' })).toBe(0n);
    expect((await fork.client.readContract({ address: platform, abi: platformAbi, functionName: 'getRequest', args: [2n] })).shares).toBe(0n);
    await capture(issuer, 'settlement-cleared');
    await investor.goto(`/#/advance/${ownAdvanceId}`); await capture(investor,'own-book-advance-repaid');
    await expect(investor.locator('.key-values div').filter({has:investor.getByText('Remaining owed',{exact:true})}).locator('dd')).toHaveText('0.00 USDG');
    await recognizeFacilityLoss(fork, facility, operator, confirm, capture);
    const lateGrace = await fork.client.readContract({ address: DEPLOYMENT.vaultA, abi: vaultAbi, functionName: 'graceOf', args: [lateAdvanceId] });
    const deadline = lateProposal.dueAt + lateGrace + 1n;
    const currentTime = (await fork.client.getBlock()).timestamp + 1n;
    const lateTimestamp = deadline > currentTime ? deadline : currentTime;
    await fork.rpc('evm_setNextBlockTimestamp', [Number(lateTimestamp)]); await fork.rpc('evm_mine');
    await partner.goto('/#/capital');
    await partner.getByRole('button',{name:'Refresh chain data'}).click();
    await expect(partner.getByRole('button',{name:'Refresh chain data'})).toBeEnabled({timeout:45000});
    await partner.getByRole('combobox', { name: 'Partner advance' }).click();
    await partner.getByRole('option', { name: new RegExp(`^Advance #${lateAdvanceId} ·`) }).click();
    await expect(partner.getByRole('button', { name: 'Mark partner advance late' })).toBeEnabled();
    await partner.getByRole('button', { name: 'Mark partner advance late' }).click(); await confirm(partner);
    expect(await fork.client.readContract({ address: DEPLOYMENT.vaultA, abi: vaultAbi, functionName: 'owedOf', args: [lateAdvanceId] })).toBe(0n);
    await capture(partner, 'partner-reserve-recovery');
    const vaultBOwner=await fork.client.readContract({address:DEPLOYMENT.vaultB,abi:vaultAbi,functionName:'owner'});
    await fork.setWallet(partner,{selected:vaultBOwner});
    await expect(partner.locator('.vault-card.selected')).toContainText('Partner vault B',{timeout:45000});
    await partner.locator('.vault-card').filter({hasText:'Partner vault A'}).click();
    await expect(partner.locator('.vault-card.selected')).toContainText('Partner vault A');
    await fork.setWallet(partner,{selected:personas.partner.address});
    await expect(partner.locator('.vault-card.selected')).toContainText('Partner vault A',{timeout:45000});
    balances.investorFinal = await usd('investor');
    await investor.goto(`/#/platform/${platform}`);
    await investor.getByRole('textbox', { name: 'Fund a position amount' }).fill('0.1');
    await investor.locator('.funding-form').filter({ has: investor.getByRole('textbox', { name: 'Fund a position amount' }) }).getByRole('button', { name: 'Review', exact: true }).click();
    const beforeAccountSwitch = fork.receipts.length;
    await fork.setWallet(investor, { selected: personas.issuer.address });
    await expect(investor.getByRole('dialog').getByRole('button', { name: 'Confirm in wallet' })).toBeDisabled();
    expect(fork.receipts.length).toBe(beforeAccountSwitch);
    await investor.getByRole('button', { name: 'Close transaction review' }).click();
    await fork.setWallet(investor, { selected: personas.investor.address });
    await investor.getByRole('button', { name: /0x7099/ }).click();
    await investor.getByRole('button', { name: 'Disconnect', exact: true }).click();
    await expect(investor.getByRole('button', { name: 'Connect wallet', exact: true }).first()).toBeVisible();
    await investor.reload();
    await expect(investor.getByRole('button', { name: 'Connect wallet', exact: true }).first()).toBeVisible();
    expect(runtimeErrors).toEqual([]);
    expect(consoleErrors).toEqual([]);
    completed = true;
  } finally {
    fork.beginClose();
    if (!completed) for (const {persona,page} of videos) {
      failurePages.push({persona,url:page.url(),text:await page.locator('body').innerText().catch(()=>''),block:await fork.client.getBlockNumber({cacheTime:0}).catch(()=>null)});
      await page.screenshot({path:resolve(artifactDir,`${persona}-failure.png`),fullPage:true}).catch(()=>{});
    }
    for (const context of contexts) await context.close().catch(e=>cleanupErrors.push(String(e)));
    for (const {persona,page} of videos) { try {const path=await page.video()?.path(); if(path) await rename(path,resolve(artifactDir,`${persona}.webm`));} catch(e){cleanupErrors.push(String(e));} }
    await fork.close().catch(e=>cleanupErrors.push(String(e)));
    const files = (await readdir(artifactDir)).filter(name => /\.(png|webm)$/.test(name));
    const artifacts = await Promise.all(files.map(async file => ({ file, sha256: createHash('sha256').update(await readFile(resolve(artifactDir, file))).digest('hex') })));
    await writeFile(resolve(artifactDir, 'manifest.json'), json({ completed, source, scope: 'LOCAL FORK ONLY: locally signed raw transactions, not public testnet writes or browser-extension verification', timestamp: new Date().toISOString(), personas: Object.fromEntries(Object.entries(personas).map(([name, account]) => [name, account.address])), receipts: fork.receipts, signatures: fork.signatures, fixtures: fork.fixtures, balances, readLatency, runtimeErrors, consoleErrors, cleanupErrors, failurePages, artifacts, limitations: ['Local EIP1193 adapter uses public Anvil mnemonic; no browser-extension wallet popup tested.', 'Engine proposal is manually filed fixture; automatic engine feed not connected.', 'Facility immutable-borrower flow uses local same-artifact deployment, not original public facility.'] }));
  }
});
